### ISSUE TITLE
BP项目梳理

### ISSUE THREAD

**Issue by BravoCiao** [gabriel-guobin/ChildAcademy#10]
![](https://cloud.githubusercontent.com/assets/23642700/25658283/a9995d30-3034-11e7-9b35-998058bccc4c.png)

1.
童行书院是郝景芳的童行计划子项目，这是一个儿童教育公益项目，在风景优美的贫困山区建立度假村、图书馆，吸引城市中高端家庭来大自然中进行亲子游，开设包括自然博物、户外、美术、天文、戏剧、故事创作等课程，旅游收入用于向当地孩子免费提供相同课程，目的是促进教育公平和对现有教育体系做补充。
应用场景：
到了寒暑假
(1)不想把小孩送去劳累密集的补习班
(2)好不容易和单位请好假，想带孩子出去亲近山水，但不想只是上车睡觉、下车拍照，希望孩子有主动的参与和产出
(3)学校课程不够全面丰富，趁假期做教育补充

2.
目标用户：大城市中高端家庭
典型用户肖像：已解决基本的生存需求，手头有余裕为小孩创造更多体验；受过良好教育、重视孩子多元培养、尊重权威、相信来自各学界科学的养育方式。

3.
痛点：
- 现有教育体系过于局限
- 农村、城市孩子教育资源分配不均
- 城市孩子无法理解农村孩子的处境，缺少共情；农村孩子看不到向更广阔领域发展的可能性，视野无法打开
- 旅游产品以纯玩乐居多，空增走马观花的经历，缺少深度参与
![](https://cloud.githubusercontent.com/assets/23642700/25658167/10f41084-3034-11e7-8d5d-d5c675cd9594.png)

4.
竞争对手：各类辅导班、工作坊
优势：
- 创始人郝景芳良好的教育背景、社会形象，有利项目推广
- 各类课程专业的师资
- 一般的辅导班、工作坊开设在城市中，童行书院将旅游度假和课程结合起来，给了既想放松、又想孩子学习知识的父母一个特别选择。

希望给大家一些启发，欢迎大家提出自己的想法、补充问题5&6

**Comment by gabriel-guobin** [comment]
对客户痛点的梳理，参考一下链接
* [ChildAcademy/ref.md at master · gabriel-guobin/ChildAcademy](https://github.com/gabriel-guobin/ChildAcademy/blob/master/ch8/ref.md)

----

@BravoCiao  非常棒的整理，尤其通过那副 痛点的树形图，分析很全面！  

可能「晴妈说」文章的影响，我之前的重点也是一直关注在教育上，看来一些亲子游资料后，略有变化，顺着这张图，交流一下。

## 谁的痛点？

如果按照景芳老师在采访中的想法， 商业和公益的评价体系要分开考虑，也就是说商业项目要比竞争对手做的还好，不会因为有公益的原因降低标准。

所以，以上痛点分析，对亲子游的用户来说，关键的是：

   - 第一条「现有教育体系过于局限」
   - 第四条「旅游产品走马观花，缺少深度参与」


## 童行书院项目的方向？

  - 不同的场景，影响 用户对服务（或产品）的需求，和对效果的预期。
  - 目前主要吸引的是原本打算亲子游的用户，他们想需求和预期是什么？BP介绍的重点是什么？
  - 如果吸引的是原本没有亲子游计划，但对孩子的教育非常关注的家长（客户流量大多来自「晴妈说」公众号的订阅者），他们想需求和预期是什么？BP介绍的重点是什么？

## 亲子游客户群体分析

- **亲子游的动机**

  1. **增加孩子见闻，开阔眼界 94%**
  1. **全家旅游放松身心 85%**
  1.  **多些时间陪孩子，促进亲子交流与感情。 70%**
  1.  培养孩子各方面的能力 45%
  1.  增强孩子独立性 32%
  1.  为学习紧张的孩子减压 26 %
  1.  让孩子解释更多的同龄伙伴 14%
  ![](https://github.com/gabriel-guobin/ChildAcademy/raw/master/ch8/markdown-img-paste-20170504212105550.png)

- **家长在亲子游中的痛点**

    - 头疼带孩子去哪里？
    - 景点不适合孩子玩
    - 不要让亲子游变成陪孩子游（父母的作用）
    - 不想走马观花的看看就会，想增加一些有特色有意义的环节。

### 面向**亲子游用户**的方向

- 显性需求：开阔孩子眼界、放松的旅行、亲子沟通互动
- 隐性需求：深度体验新鲜的文化，孩子获得能力上的提升
- 预期：，对大人和孩子，放松是第一位的，又想获得更多新鲜的体验
- BP重点：强调旅行中，通过童行书院的深度体验，对自然的发现和热爱、对家庭成员情感的促进

#### 面向**关注孩子教育用户**的方向

- 显性需求：通过户外活动的课程，培养孩子对STEAM的兴趣
- 隐性需求：家长自身也获得成长
- 预期：期待孩子能获得行动上的改变，从对学习没兴趣到能主动在传统学校学习中发现乐趣
- BP重点：强调旅行中，童行书院的教育资源，以及作为补充的「童行星球」计划

### 我们要解决的重点问题
- 竞争优势：  
bravo上面已经分析的很准确了。还有一点就是驻地教师的特点也是与竞争对手最大的区别。由于这些支教老师精心选拔，有多元的背景，另外最重要的他们工作的初心并非以赚钱为目的，而是对孩子对教育的热爱，所以旅行过程中营造的氛围和体验也会不一样。
- 注意的问题：  
由于主要客户面向的是亲子游家庭，所以BP的介绍中，涉及的话题或者教育的内容太多会与他们「希望放松」的预期向违背

---

先草草写了一些，想到继续补充。。。
