### ISSUE TITLE
ch8 BP故事方向和一些碎片想法

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#12]
## 童行书院 BP的方向分析

1. 与市场上亲子游最大的区别 
	- 书院 VS 户外野营
	- 教师 VS 导游

2. 故事场景设定
注意故事的氛围和基调与表达主题的一致

- 自律 ：重点在教育
- 享乐：重点在旅游和放松
 
参考这篇文章：* [可口可乐新slogan：如何打死自律小人](http://mp.weixin.qq.com/s?src=3&timestamp=1494061820&ver=1&signature=jEOLD23FBrHu6pP7IvuI6Vxs1zCRERN1gmwEjj4TdyuEuwbbi752Fmf6Tn-SCIAWaEDA7HhDGSGDTjpKO2MZxJQzV60fK4AKKjeF8hiWYfScJL3l5GxAEyg3vivqqjBtuz75qFbOZVyDoEAZM0CZ6g==)

3. 注意故事场景与观看者的共鸣     参考李叫兽的文章  * [mp.weixin.qq.com/s?__biz=MzA5NTMxOTczOA==&mid=400345774&idx=1&sn=2edb97df6f8b1581cdabbb3716f5e5a4&scene=21#wechat_redirect](http://mp.weixin.qq.com/s?__biz=MzA5NTMxOTczOA==&mid=400345774&idx=1&sn=2edb97df6f8b1581cdabbb3716f5e5a4&scene=21#wechat_redirect)
4. 文案的战略重点

怎样突出与其他亲子游产品的差异化竞争呢？

亲子游竞争者：麦淘
http://www.maitao.com/about/#about-us

自己的战略是什么？

战略在于教育资源的优势，期待的是培养孩子的创造力。

* [小孩子才看文案，大人只看策略！](http://mp.weixin.qq.com/s?src=3&timestamp=1494061820&ver=1&signature=5Vhf2bfnuguMXRRDa1JQr8Sq-WE3IL9EYYeNu3da52rpNsorV48ZZGAR9MrTdq3Ra0mLPjkzgdiaL4hhX5vewHDS5HrYuEHTReuEqPe94rP8M8Ct23HyZ9GWphRMqmMFZuasras6kmdSMzPYG49XUsWpZ1ZT7Gd3cNw7x4gAL4c=)

战略重点在于施教者， 「人」 的关键因素上，以及这个人能获得的支持。

人才   是核心竞争力  

不是把传统课堂的教育搬到户外
而是一群怀揣诗和远方的造梦者，用爱为孩子搭建的创造力平台

其他参考：

* [我希望你也能写出这么好的文案（收藏版）](http://mp.weixin.qq.com/s?src=3&timestamp=1494146170&ver=1&signature=rderR6feN9dCVp-pVKeRXNUSnai0XVmj3Ga-xN6wMSF*qS0hnNhbORM3PMqyTWUNuIVS686JLHtM1ipr*HbzrO1JUC2vwvMe5BlArMacXSkZrI8xWzlomfSp9ta5E2OfCpLPkargZQ7pKoWrPZeltgKmsfCeAn9s5f4m1Z-m9NU=)

* [130句App Slogan，句句都是牛逼的洞察！](http://mp.weixin.qq.com/s?__biz=MjM5ODQzMTk3MQ==&mid=2652113944&idx=1&sn=f375ef8ef5b1e841a493b0844f17a124&chksm=bd2a71948a5df882202d201913d4c22b866a5dea445dbb68e745c90564a3dd95336c854fb31a&mpshare=1)

* [抱歉上次没把麦淘写明白，这篇我们把亲子游的秘密全挖出来](http://weibo.com/ttarticle/p/show?id=2309614080468852123367)

* [『广告界年度盛典』2016年最值得关注十大广告文案案例](http://mp.weixin.qq.com/s?__biz=MjM5ODQzMTk3MQ==&mid=2652113663&idx=1&sn=8bd897fb8f5be32ba16677efab6f8661&chksm=bd2a77738a5dfe657357b727571e1504fe6f0f5312a140b225ff61fccfc4e1ba9d35682f5faa&scene=21#wechat_redirect)

## 文案碎片

孩子的世界：清新、陌生而美丽，
孩子的感受：惊奇和刺激

成人的世界：秩序、规则、常识
大多数成人：对叹为观止的感受力已经麻木或丧失

图片：放大镜下的的雪花的世界
文字：我们由于看什么都过于匆忙、只见整体不见局部、因而通常会错失这些美好事物。

希望赐予世界上每个孩子对事物的惊奇之心，而且终其一生都无法被摧毁，能够有效的对抗以后岁月中的倦怠和幻灭，拜托一切虚伪表象，不至于原理蜂窝煤内心的力量源泉。

一个孩子要保持他的惊奇之心，他至少得有一个成年人的陪伴，与她一起重新发现我们生活的这个世界的快乐、激动和神秘。

父母：
一方面要面对孩子的热切、敏感的心灵，
另一方面又要面对一个有着复杂自然特性的世界时，
他们往往会感到无力，

我们居住的这个世界中的生命是如此多样、如此陌生，以致似乎无法将其用秩序和常识来归纳，
这时他们便以一种自我挫败的心态宣称：“我怎么可能教我的孩子了解大自然呢——哎呀，我连两只鸟都区分不了！”

对于孩子和想要引导孩子的父母来说，感知远比认知重要得多，或者说“知道”的重要性还不及“感受”的一半。

客观事实是日后生产出知识和智慧的种子，
情感和感受就是种子赖以生长的沃土，

而儿童时代的早期是土壤的准备时期。一旦唤起了对美的感受，与对新鲜和未知事物的兴奋感，同情、怜悯、赞赏或爱的情感
——我们便会希望获得使我们产生了情感的这些事情的有关知识。

这样的学习，意义会更加持久。
为孩子铺就一条渴望知识的道路，
远比向他反复灌输他尚未准备好吸收的事实更为重要。

**Comment by gabriel-guobin** [comment]
考虑到童行书院与目前自由行产品的核心差异，在人的因素上。

**宣传的战略重点在于施教者**， 「人」 的关键因素上
**人 是核心竞争力** （间接提到为公益而不是为赚钱）


**不是把课堂搬到户外
而是自由创造的平台
由一群不甘平庸的造梦者，为山区孩子和城市孩子共同搭建的「世外桃源」。**

---
以下再摘取上面比较重要的两个链接，解释下上面想法的来源

1. 好文案本质上并不是创意、文采和生动，而是能不能服务于企业的正确战略。

  * [【李叫兽】别跟我谈文案本身，谢谢](http://mp.weixin.qq.com/s/5ofvJQla3I8kt5XWYfcAzQ)
  
 **启发：童行书院与竞争对手相比，优势应该是教育，那这个优势怎样体现的呢？**

2. 传统亲子游行业，正在往教育的方向转移，最大的难度在于「老师」，这也是亲子游过程中，决定孩子和家长体验的关键因素。

  * [把亲子游的秘密全挖出来](http://weibo.com/ttarticle/p/show?id=2309614080468852123367)
  >TBO：提一个你认为亲子游行业目前最大的弊病，以及您设想的解决方法

  >对于亲子游来说，依据不同的主题还有路线，或许在领队和导游的基础上，还需要一些专业的老师，给孩子们讲解不同的知识。这部分成本势必要算入亲子路线的成本中，所以提到亲子游，大家都会觉得价格高。

  >如果亲子行业里的导游可以转换为专业的导师，不再是稀缺人才，那么亲子游市场一定会有一些成本的降低。这样的话，行业可能就可以真正做到大众满意。

  **启发：其他同类产品，最稀缺的资源反而是「童行书院」最核心的实力，而且从 「老师」 切入，可以顺便带出此项目公益的部分。**

**Comment by 2Forest** [comment]
非常同意“感知比认知重要。”这一点我觉得对3-12年龄的孩子是非常切合的。所以甚至可以提炼成一句宣传语。

与常规亲子游相比，童行有老师；相对于其他有老师的亲子游，童行的优势在于老师都经过六个月全面、专业的培训，长期驻扎在当地，能更好的结合当地情况带领孩子感知一方水土。长达六个月的全面培训，是慢工出细活。我们对孩子负责，所以舍得“浪费时间”先修炼老师。

场景的话我觉得之前夏霜说的那个场景很好。
