### ISSUE TITLE
ch9 卡片写作 段落一 ：我带你去。。

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#14]
* [ 此部分思路和结构，参考[箱行者]的文案和视频效果](https://github.com/gabriel-guobin/ChildAcademy/issues/13#issuecomment-299734233)

**以记忆生存效应的风景激发旅行的渴望，介绍童行书院的三个驻点**

## 格式

我带你去 。。。（贵州 楼那的特色风景）

我带你去 。。。 （张家口崇礼的雪景）

我带你去 。。。（贵州紫云的星空）

---
@oliviayx  可在此基础上发挥创意，拆分成更小的卡片，组织大家讨论，快速写作

**Comment by oliviayx** [comment]
我带你去桃花源   
探访阡陌交通 
在田园悠然牧歌
把乡愁留在楼纳 

我带你去跳花圣地
偶遇一米阳光
在中洞苗寨推磨碾谷
把穴居生活留在紫云

我带你去草原天路  
约会漫山野花
在雪场炸开狍子的尾巴
把纯净与灿烂还给崇礼

---
guobin: 洛洛写的好美，三个段落的结构齐整，也很有画面感。  
建议慢改的时候试着配上图片和音乐，效果更好。   

崇礼那段看到了两个画面，如果只保留一个更喜欢雪场那只狍子😁
试着给家人朗读了一下，果然被我的声音转述出来，灵气少了好多。大家也可以试着把自己的朗读录下来，分享给别人听。
@oliviayx

**Comment by oliviayx** [comment]
我带你去桃花源
探访阡陌交通
在田园悠然牧歌
把乡愁留在楼纳

我带你去跳花圣地
偶遇一米阳光
在中洞苗寨推磨碾谷
把穴居生活留在紫云

我带你去冰雪之乡
等候骤雪初霁
在雪场炸开狍子的尾巴
把光华与纯净还给崇礼

修改了最后一段，尽量将画面统一在一个意象中，想要利用时空变形去修改，但是遇到了瓶颈，希望大家多给点意见。
