### ISSUE TITLE
ch9 卡片写作 段落二 ：活动场景

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#15]
#### 参考格式

我带你和孩子们。。。。（突出亲子活动）

我带孩子们。。。（感受自然、创造力游戏）

孩子们自由玩耍时，我带你 。。。（文化沙龙，诗酒茶）

---

* 此部分关于「感知」的内容，可以参考[惊奇之心](https://github.com/gabriel-guobin/ChildAcademy/blob/master/ch8/The%20Sense%20of%20Wonder.md)

>“感知”是真正的热爱：“感知远比认知重要得多”，“情感和感受就是种子赖以生长的沃土”

---
@MuDemuder 可在此基础上发挥创意，拆分成更小的卡片，组织大家讨论，快速写作

**Comment by MuDemuder** [comment]
（家长视角）

你渴望童真
增进情感
请抓住孩子的尾巴
一同尝布依族乡愁
摘苗家星星
画雪天狍子

你渴望难得的休闲
请穿上田坝织成的新衣
文化沙龙
诗酒茶
或者
看着孩子

孩子
正在独立地
将创意变成作品
是一幅画，一篇文章，一个实验
或者一棵草，一朵花，一片星空
然后
与其他孩子协作
触发火花
相互发问
相互思考
多次以后
形成自我的头脑
击败怪兽和原始的头脑
