### ISSUE TITLE
ch9 卡片写作 段落三 ：我是谁（通过老师引出童行书院）

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#16]
## 第三: 同行书院的支教老师介绍，团队介绍，愿景介绍

**参考格式：**

我曾经是。。。。（突出支教老师的多元身份和文化）
我曾经是。。。。（突出支教老师的诗和远方）

我是。。。。（童行书院的支教老师）

我们要做的是。。。（补充说明童行书院的计划）

---
此部分相对赋予的意义较多。

考虑到童行书院与目前自由行产品的核心差异，在于「教师」的因素上。

宣传的战略重点在于施教者， 「人」 是核心竞争力 （间接提到内在动机是公益而非赚钱）

不是把课堂搬到户外
而是自由创造的平台，

由一群不甘平庸的造梦者，为山区孩子和城市孩子共同搭建的「世外桃源」。

- 战略方向：教师的公益初心和多元化的能力，是「童行书院」与亲子游产品最大的差异，也是最大的优势，

- 表现形式：童行书院老师以第一人称「我」的口吻把观众带入场景，通过介绍我曾经是谁（**一句话故事**）、现在是谁（提出指教老师和童行团队），来暗示教育理念（采用 2+2 ，不直接说出4）

- 「一句话故事」的文案参考
  * [不扯淡，只谈钱，这支广告很实在](http://mp.weixin.qq.com/s?__biz=MzA4MDMzMTE3Nw==&mid=208857690&idx=1&sn=ffb6363c02ebff6530a3a90d55b5d5a0&mpshare=1&scene=1&srcid=0508psfUCApPBKFLMxCaoWSa#rd)
  * [首次曝光 | 蚂蚁金服46张走心海报创作全历程](http://mp.weixin.qq.com/s?__biz=MjM5NjEzNDI4MA==&mid=2652079847&idx=1&sn=efc81c91a4d2d629b694ef070a200225&chksm=bd0aca008a7d431622b57d5c72300943e4319a98f498ddcbb975a6adbcec7f9f89d6b12911d0&mpshare=1&scene=1&srcid=05084yTYFtrFYb57RlMw0tpg#rd)

---
@xiashuang613 可在此基础上发挥创意，拆分成更小的卡片，组织大家讨论，快速写作

**Comment by xiashuang613** [comment]
我曾经是一个美术工作者，
常常做的事是穿过画布，
静静站在梵高的星空下
和他握手言和；
或者
偷偷跑进莫奈的池塘，
数一数未开的睡莲。

我开过画廊，办过展
我在寻找，属于这块土地的艺术


我曾经是一个编剧，
常常在等故事、
等不是哈姆雷特的故事，
写剧本，
写要读很多书才能看懂的剧目；
剧本上写别人的故事，
别人的故事里没有我，

我参加过电影节，获过奖，
我想创造，和我们生命有联结的故事


在童行书院，
我不是美术老师，
常常带孩子
造艘船，就敢
遨游不是梵高，
是在紫云的星海

简单装备，就能
钻进楼纳的花海
追寻蜜蜂的飞行路线，
画出振翅的蝴蝶，
我们是追蜂人，
是春去秋来的见证者

在童行书院
我不教写作，
却常常陪伴，
和孩子们一起
赤脚摸摸土地的温度
伸出手划开风的紧张
张开耳朵听喃喃细语

认识每个人，每件器物，
年长的、新鲜的
和他们打招呼。
过去的，现在的
聆听他们的故事，
眉目间的神情，
是恒久的欢喜和谦卑
我们是故事中的人
无需执笔，却写下未来。

童行书院
没有教知识的老师，
我们只有陪伴者和协作者，
顺着孩子的手指，
我们看见他的看见；

我们的教室在大自然，
没有固定课表，
四季和风，
会告诉我们如何做最好的安排

博物、美术、天文、戏剧，
承载人类记忆的美，
我们和所有的孩子——
分享美，
并把美刻进生命的基因。


楼纳、紫云、崇礼，
童行书院在这里
和你同行
遇见美好的未来！

**Comment by xiashuang613** [comment]
**关于老师角色**
选了两个人物，一个是画家，一个是编剧。美术和戏剧，都是童行书院对外宣传提到的内容，不会跑的太远。我选择美术，是因为对星空的很执着——梵高的星空最有名啦，从原来的画星空，之后也可以是看星空，相呼应。选择编剧，是因为真的有一个编剧加入楼纳团队，但在写的过程并没有很顺利，编剧本身是写故事的人，有一些细致的还需要推敲，在童行中，就不是手写，而侧重在感受力上。写和感受力，是一体两面吧。


**关于童行书院的描述**
两个老师的身份转换，也一定程度上说明了童行书院的内容。在这部分，从“书院”这两个词，大家简单想到的就是教师、学生、教室、课表等等信息，我也就此做直接的反——正书写来进一步说明童行书院了。
倒数第二段，算是升华部分，我想到的是，“美”这个词，教育最终的目的是成为独立的个体，独立的个体不管置于何处何时，不放弃对美的追寻，能够把美刻进生命的，成为基因密码一部分应该比较厉害吧。

**关于最后一段**
之前都只提到童行书院的两个地方，嵌在文本中提到紫云、楼纳（紫云未来的方向是侧重天文，楼纳我看过有油菜花，所以讲紫云的星海，楼纳的花田）。最后一段就将三个地方列出来，既传统又老套。实在是想不出来了。

以上是部分说明，欢迎讨论。我也再继续修改。

**Comment by gabriel-guobin** [comment]
### 目前BP方案不足
三个段落之间联系不够紧密。整体的BP缺乏故事性。

### 改善的方案

- 整体结构还是三段 「我带你去（地点），我带你做（事件），我是谁（过去，现在）」。
- 但是纵向，以[人物]联系起来，按照人物的特点分别展开（可以暂时设置两个人物：画家和编剧）。
