### ISSUE TITLE
ch9 卡片写作 BP开头 ：一句话吸引注意

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#17]
如何用文案的第一句话抓住 注意力 ？

比如：
> 你期望 孩子的记忆里 是网络热词还是古典诗词

优点：
1， 与我相关-绑定“关注圈内的信息”；
2， 反差-让关注圈内的信息出现变化

>在长期的进化中，为了生存，大脑只关心与自己密切相关的，并且对反差、变化类的信息异常关心.
![](http://mmbiz.qpic.cn/mmbiz/As7mscS0UODkic9NG0II0ujo8gc7lgMQO3tNxlq8uDredib4A0icLlFO5zXfw3UmXnK7yFSPzHiciciba6RFR0fkmCRQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1)

---
参考资料：
* [【李叫兽】解冻文案III：90%营销人写文案前的第一个错误](http://mp.weixin.qq.com/s?__biz=MzA5NTMxOTczOA==&mid=401445140&idx=1&sn=a3fb72dc6738c9307bc10af910e819aa&mpshare=1&scene=24&srcid=0508QdN5JfRvdYwxGLvzsu5c#rd)

**Comment by 2Forest** [comment]
写的三个连在一起的，发在这里吧。

城市里霓虹闪烁，
你的心底却有另一种璀璨。
每天奔忙在水泥森林，
你的心却驰骋在山间。
头脑淹没在信息的海洋，
灵魂却在渴望桃花源。
看着孩子因为学业日渐锁紧的眉头，
你盼望有一个空间，
可以安全放飞孩子，
帮助他/她重展笑颜。
在这里，
这里，
这里，（三个地方标志性图片）
我们懂你，
我们等你。

之前我是一名电影编剧，
现在我是童行书院的老师，
我会带你和孩子，
通过戏剧发现更多可能。

之前我是一名设计师，
现在我是童行书院的老师，
我会带你和孩子，
在图案和设计中探索新的答案。

。。。


这样的景致你也许见过，（配图）
这样的风俗你也许早已听说，
但这样的老师，
全面准备六个月只为遇见你，
你一定没见过。
这样的旅行，
精心设计只为陪伴你，
你一定没见过。

我们，
在楼纳，
在紫云，
在崇礼，
陪你，
陪孩子，
一起发现世界本来的样子，
一起遇见更接近自然的自己。

**Comment by gabriel-guobin** [comment]
想把这句话，改成一个开头，大家一起来改写吧。

>真正的探索之旅并不在于寻找新的风景，而是要有新的眼光。
>The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.
>——马赛尔·普鲁斯特（Marcel Proust)《追忆似水年华》作者

* [通过森林幼儿园案例谈儿童教育_真正的探索之旅并不在于发现新领_宝宝树](http://www.babytree.com/community/dabenying/topic_73477608.html)
