### ISSUE TITLE
搜图网站收集

### ISSUE THREAD

**Issue by BravoCiao** [gabriel-guobin/ChildAcademy#19]
许岑keynote上提到的三个网站:
- https://www.shutterstock.com/(图片全，无版权担忧)
- https://www.dreamstime.com/
- http://www.istockphoto.com/gb
其他:
- Google
- Pinterest
我这里按我自己的思路写文案遇到瓶颈了,现在把找图网站放出来,有合适的留意着,我最后汇总做keynote.
注意图片画质越高越好

@gabriel-guobin 另一个issue中的补充：
* [高清视频素材网站有那些？？ - 知乎](https://www.zhihu.com/question/22449745)

* [Free stock videos – Pexels Videos](https://videos.pexels.com/)

* [Distill: Free HD Stock Video & HD Video Clips](http://www.wedistill.io/categories/nature)

* [Unsplash | Free High-Resolution Photos](https://unsplash.com/)

----

5/12  guobin 更新

部分图片资源上传到百度网盘了

链接: http://pan.baidu.com/s/1bpiY3L1
密码: kgr9

**Comment by gabriel-guobin** [comment]
以下为童行书院驻点 相关的图文收集，会持续更新

贵州楼纳（长途旅行试点）
---
- 地点：楼纳（国际建筑师小镇）
- 活动：借助自然地理条件，以山水自然探索和民间艺术为主要旅行产品

* [拥抱自然，惊喜连连，快来楼纳过大年！ - 每日热文( www.irewen.net)](http://www.irewen.net/news_baby/46755.html)

* [李兴钢：露营基地服务中心 | VILLAGE VISION?楼纳实践 - UED - 微读吧](http://www.weidu8.net/wx/1000149036218691)


贵州紫云（长途旅行试点）
---
- 地点：“星空下”帐篷酒店负责度假村开发、场地设计
- 活动：设计打包“天文+自然+艺术”亲子课；结合当地文化民俗开设工作坊。

* [星空下帐篷酒店](http://www.xingkongxia.cn/address.html)
* [他放弃了五星级酒店来到群山峻岭间，只为悬崖之上伸手可摘星](http://mp.weixin.qq.com/s?__biz=MjM5MDcxOTk4OA==&mid=2650262009&idx=1&sn=bb3db5cada828457d3dfeb7918ffa33c&chksm=be43e36289346a748e99ddfab3297508d8e0d96167b02e7b4156b27d6d116199337d50632854#rd)
* [紫云有一个2.5亿元的神秘项目正在建设，它竟然与星空有关！](http://weibo.com/ttarticle/p/show?id=2309404057338360276749)
* [**视频**格凸河景区2017年宣传视频 - YouTube](https://www.youtube.com/watch?v=V9dFvGU6bSA)


张家口崇礼万龙滑雪场（短期体验课试点）
---
- 地点：与万龙度假村合作（赞助场地和建筑建设）  
              熊向军及其工作室提供场地设计和内部装修建设

- 活动：以“未来科技和科幻”为主题，建立机器人展厅，拓展思维。

**Comment by gabriel-guobin** [comment]
雪花
---

* [雪 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E9%9B%AA)

![](http://www.natgeomedia.com/wp-content/uploads/2016/04/%E9%9B%AA%E8%8A%B1%E7%B5%90%E6%99%B6.jpg)

### 我带你去看「来自天空的信使」，站在飞扬的雪花中，为你朗诵徐志摩《雪花的快乐》
![](http://ipsm.hner.cn/xxpd/tjxx/shang/kx/4/05/8/8_1/8_1_mt/image/tkx4s080128031.jpg)

* [徐志摩-雪花的快乐 (赏析)](http://www.artsdome.com/books/xzm/003.htm)
>假如我是一朵雪花，
    翩翩的在半空里潇洒，
    　我一定认清我的方向——
    　飞扬，飞扬，飞扬，——
    这地面上有我的方向。
    不去那冷寞的幽谷，
    不去那凄清的山麓，
    　也不上荒街去惆怅——
    　飞扬，飞扬，飞扬，——
    你看，我有我的方向！
    在半空里娟娟的飞舞，
    认明了那清幽的住处，
    　等着她来花园里探望——
    　飞扬，飞扬，飞扬，——
    啊，她身上有朱砂梅的清香！
    　那时我凭借我的身轻，
    盈盈的，沾住了她的衣襟，
    　贴近她柔波似的心胸——
    　消溶，消溶，消溶——
    溶入了她柔波似的心胸！    



* [显微镜下的雪花真漂亮](http://news.xinhuanet.com/forum/2005-01/30/content_2519823.htm)
>日本物理学家中谷宇吉郎博士曾把雪比做“**来自天空的信使**”，并查明千差万别的雪的结晶形式取决于高空气温高低和水蒸气的多少。

**Comment by gabriel-guobin** [comment]
部分图片资源上传到百度网盘了

链接: http://pan.baidu.com/s/1bpiY3L1 
密码: kgr9

**Comment by gabriel-guobin** [comment]
星空
---

## 带领孩子们穿过过画布，站在梵高的星空下，感受时间与空间的对话

（配图：1 星空视频，梵高的《星夜》）

>当我画一个太阳，我希望人们感觉它在以惊人的速度旋转，正在发出骇人的光热巨浪。当我画一片麦田，我希望人们感觉到麦子正朝着它们最后的成熟和绽放努力。当我画一棵苹果树，我希望人们能感觉到苹果里面的果汁正把苹果皮撑开，果核中的种子正在为结出果实奋进。当我画一个男人，我就要画出他滔滔的一生。如果生活中不再有某种无限的、深刻的、真实的东西，我将不再眷恋人间。

>——《亲爱的提奥》文森特·梵高

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/757px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg)


![default](https://cloud.githubusercontent.com/assets/22133106/25992018/e1abebc0-3737-11e7-9464-28a48d661d02.jpg)

[星空视频——延时摄影](https://videos.pexels.com/videos/starry-sky-timelapse-472)

你可能想知道它们的名字，

而我会分享的

是对他们的热爱，和对未知的思考

我教你用天文望远镜捕捉星星的笑脸，

然后熄灭篝火，围坐在星空下，听每个孩子与星星的故事。。。

**Comment by gabriel-guobin** [comment]
月亮
---

傍晚我带你到山顶，与月亮一起玩耍。

![](https://s-media-cache-ak0.pinimg.com/564x/6c/a7/00/6ca7004c64fce36790cb4969c297f558.jpg)

![](https://s-media-cache-ak0.pinimg.com/564x/37/24/de/3724de89c057ae01e5d9ff49d72dad99.jpg)

![](https://s-media-cache-ak0.pinimg.com/564x/9d/dd/04/9ddd040c7003b4f9a7753000b03862a5.jpg)

![](http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl=http://mmbiz.qpic.cn/mmbiz_jpg/kcicTRa7sQreKiaYKlmgocvwNuGDGRPiaic50fVWZDByXIwSAcicUyCS7tmXFgKL0cwUB0vXaYatg96jX9cUToxT8eA/0?wx_fmt=jpeg)


* [Moon Games](http://digital-photography-school.com/moon-games/)
