### ISSUE TITLE
ch5 项目主线及最小故事讨论

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#2]
## 本周任务
- 项目主线 
    - 面向的对象是谁？
    - 以怎样的视角来讲述？
- 最小故事
    - 事件 1 2 3
- 故事隐喻
     - 希望有一个切合主题的意向，贯穿整个故事

请大家根据认知写作原理，生发自己的创意。于本**周五19：42前提交到本issue**，

## 线上讨论
**周六晚约19：42大家线上会议讨论各自的想法**。
（最终依据大家安排确定为周六晚上某时间段，北京伙伴若方便可在同一时间线下聚会共同参与远程讨论）

- 形式  
   阳老说过头脑风 暴效率较低，本次讨论尝试以STD算子（S：尺寸，T：时间，C：成本）对大家的故事进行讨论和重组。各位创建故事时也考虑此理论（参考《创新算法》）

- 时间 约1小时30分钟
    初步打算每人3分钟说明5分钟答疑。然后大家共同讨论30分钟，结论梳理30分钟，

- 会议记录整理和录音
    - 可自主报名（大家自己看懂就好，不需要向写作班答疑整理那么花精力）
    - 使用工具（没想好，大家可推荐）

期待大家的思维碰撞。

**Comment by gabriel-guobin** [comment]
​提供给大家一个场外人员对原来最小故事的批评和建议。
建议和角度不一定正确，但是给我们的讨论垫个基调。
这种尖锐和挑剔才能成就我们好的作品。大家畅所欲言，多提出自己的想法哦。

主旨和书院的初衷没有很好的契合。场景一是书院的两个目的，不过结尾是阶级融合，就有点牵强，阶级一直都有，至少很长一段时间里，但我们能做的是给那些孩子一个机会。个人觉得看完这个片子从普通人的角度来说，应该达到的目的：这个地方是亲子户外旅行的首选地，就像我们一说到旅行就想到三亚，让人看了很想立马带孩子去。让人有消费冲动，这才是书院能不断发展的经济来源就像大家看到‘’大眼睛‘’孩子的图片，有想帮助他们的冲动。帮助落后地区的儿童，是书院不同与其他商业旅游的独特之处。抓住人心理的优越感，促进消费，达到目的。

总体来讲故事性不强，没有冲突，平淡无奇。三个板块叙事逻辑是：有什么（孩子现状），要什么（书院内容），怎么做（畅想）。其实如果换个顺序，也许就会好很多：要什么（理想的孩子成长环境），有什么（现状的无奈），怎么做（来童行书院呀）。最常见的商业模式。

好吧，发现我是商业项目做多了，功利性太强。不过一个片子做的能够打动人，或者能够吸引人都算成功吧。明确做这个片子的目的是什么，是介绍书院？招聘？推销？还是……目的不同，文案风格，叙事逻辑都会不同。即使不做这个，其它项目希望能给到一点参考。

​

在 2017年4月12日 下午10:37，Gabriel.Guo <notifications@github.com>写道：

**Comment by gabriel-guobin** [comment]
内部链接参考：
* [BP 制作 QA 集锦](https://github.com/AIWriter/Writer004/wiki/InfoBPQA#0-%E5%A5%BD-bp-%E7%9A%84%E7%89%B9%E7%82%B9)

* [BP 制作建议](https://github.com/AIWriter/Writer004/wiki/InfoBPTips#3-bp-%E5%88%B6%E4%BD%9C%E7%9A%84%E4%B8%89%E4%B8%AA%E5%A5%97%E8%B7%AF)

**Comment by xgh007** [comment]
既然要写一个故事，人物和事件必不可少，人物和事件到最后必然要突出文章的主旨。故事中的人物，个人希望他是一个带有社会使命感，性格强硬，不会被困难压倒的这么一个人，希望他前期是具备热情，理想化的那么一个人。性格大大咧咧，乐观且富有爱心，爱心是一个升华的点，最终留下来支教的内在能量的源泉。所以如果我写的话，性格上的强硬和勇气也要表现出来，做支教，不是一件理想化的事情，虽然你可以想得理想化。故事会突出人，而淡化学院，学院在故事里的角色就是一个主人公的平台，额。。若是要突出学院，就再建立一个人物角色：学院的管理者。或者说在人物升华之后，直接建立支教平台。行为的主导者必须是成人，孩子，我则希望是以群体出现，孩子的模因要丰富，足以感染成人。	

事件则想到的是教育的传承和对孩童的关爱，一个老师因种种原因离开，她因种种原因而到来，这一部分可以有想象的空间，刻画一个强有力的模因：比如死亡，爱情。虽然很老套，但若是编的好，就可以在最大程度上感染他人。

希望他是一个真实故事的改编。因真实的故事，自有千钧之力，这个要找素材。

最小故事的联想
1：主人公是一个小丫头，教育专业毕业，想体现自己的人生价值，申请前来同行书院支教

2：发现城里和农村小孩彼此无法真正融合，管理者过于理想化，很多方面表现懦弱，而很多前来支教的人只是为了体验人生，成全自己，内心失望，刚好这时候，男朋友也不理解，导致分手。她去和管理者聊天，对峙，甚至发生冲突，最终扬长而去，此时主人公已接近崩溃，接着发生一个故事，让她重燃对生命的希望，对教育的热情。

3：反转，她发现管理者有难言的苦衷，默默得为她争取了很多，最后坚定的走到了一起，以此为一生的事业。希望给故事一个开放性的结局，就是反转之后不要给结局。

故事隐喻1：小孩的感情很好骗，你对他好，他就喜欢你，所以不要辜负孩子的一片真心
故事隐喻2：人都是一开始的脆弱，要使脆弱者变得坚强，除了生活的锤子，还需要强烈的内在动机，如何焕发内在动机，是一个人幸福的源泉
故事隐喻3：支教不是爱心泛滥，而是一份社会主义的伟大事业。

最后想到的主题是：献给那些在一线支教的老师们。

 额。。。。。仅供参考，感觉太过片面和剧情化了，故事如果不够丰满，主题就可能有堆砌感情的嫌疑。

**Comment by gabriel-guobin** [comment]
我的最小故事 怎么想都有漏洞，大家也可以简单把自己思考的一些片段或者框架写下来。不一定要有完整的最小故事和隐喻。重要是思考过后，再一起讨论，更容易共鸣。

大家可以顺着这个问题，想一下自己的答案。

####	第二讲的最小行动：「多背一公斤」、「陪孩子读诗」这样的品牌设计的优点是什么？为什么公益项目这么设计会有很多好处？

#### 更多灵感可以从这些问题中 找找

##### 如何在 BP 中运用课程原理？
可对照此问题清单和你的团队伙伴一起探讨。
1.	第二讲的最小故事：为什么有的 BP给我的故事感不强？有的 BP 我很愿意去传播？
2.	第二讲的最小行动：「多背一公斤」、「陪孩子读诗」这样的品牌设计的优点是什么？为什么公益项目这么设计会有很多好处？
3.	第二讲的组块：哪些同学的BP违背了组块原理？
4.	第二讲的远距联想：为什么我越觉得新鲜，越觉得有创造力的BP，它的远距联想越强？为什么，「有趣/社交」这类大词要尽量少用？
5.	第三讲的情感指数：为什么我会感动 陪孩子读诗/你宠我宠 这样的温馨之作，却看到太多数字的作品，容易睡着？哪些同学的大作业的情感指数极高？哪些同学的情感指数还不够？如果我来写对方的大作业，我会如何改善？
6.	第三讲的大脑爱脑补：为什么科技范的BP，反而不要反复讲自己的科技多么牛逼，而是呈现2+2，而非直接告诉读者2+2=4 这样的结论？
7.	第四讲的隐喻：为什么「蝴蝶社群」、「黄油相机」这样的隐喻，我们更容易记忆？
8.	第四讲的框架：为什么BP，采取积极框架，更容易传播？
9.	第五讲的文采：为什么拼接诗句，更容易形成文采？如：陪孩子读诗。又如，怎样采取时空变形，能让自己的文字更有文采？
10.	第六讲的文采：对于一些非生活用品，如何借助修辞认识，提高文采？如，「真卿造字」的下一步改进方向。
11.	第七讲的故事种子：为什么故事种子只选一个而非多个？
12.	第七讲的意向性：为什么不少BP的趣味性、故事性还是不强？并且写的时候没有发现？
13.	第七讲的裁剪枝叶：为什么有的BP主干还是不够清晰，采取了「清单式写作」而非突出故事？

**Comment by MuDemuder** [comment]
首先重点是，我们要做一个怎样的？是推广这个项目，还是招聘老师。

- 书院角度：若按照书院的设想，其实很多内容都有了，我们可以找一个小点，足够吸引人，不用面面俱到。

	- 工作是怎样的（搬运工，可扩充）：
		- 培训
		- 旅行
			- 亲子课程
			- 冬夏令营
		- 公益
			- 课外教育
			- 送资源入校
			- 联络接待
	- 那么学院最吸引人的是哪一点？与其他工作最大区别在哪？系统化再学习、舒适工作环境、自由的工作氛围、还是其余的？
		- 对象：我暂时选择了 想给自己2年缓冲期的应届毕业生。
			- 故事一：毕业后是继续深造还是寻找工作，是留在大城市还是回老家。选择困境。
			- 故事二：来书院，与孩童一起。
			- 故事三：留下悬疑，你会选择什么？
			- 分析：有点平淡，没有亮点。
		- 说到孩童，我想起来孩童区别成年人特有的品质：想象力丰富，远距联想棒，那从这入手。
			- 故事一：思想才是人保持年轻的源泉，那如何追求？打破僵局。
			- 故事二：与儿童在一起，与大自然在一起，学习天文地理，将知识自我组装。
			- 故事三：寻找到思想，来书院吧。
	- 继续完善。先匿了。。。

**Comment by gabriel-guobin** [comment]
@MuDemuder 的疑问，也是我一直纠结的重点。之前想的故事也都是从教师的视角出发。顺着课程组提供的问题清单，梳理思路如下：


- 问题：最小行动：「多背一公斤」、「陪孩子读诗」这样的品牌设计的优点是什么？为什么公益项目这么设计会有很多好处？
- 我想到的答案：
    - 优点：认知负荷小，有明确的行动指向。
    - 公益项目这么设计的好处：好记，看标题就知道是什么。易行：不增加心理负担和行动上的难度。

- 对两个项目的分析：
	- 「多背一公斤」：如果`去旅行`，那么`多背一公斤`。 实现效果：既不妨碍旅行，又帮助山区孩子读书。
	- 「陪孩子读诗」：如果`跟孩子在一玩`，那么`陪孩子读诗`。 实现效果：既享受亲子时光，又让孩子爱上文学。

- 顺着这个思路分析一下，童行书院
	- 「童行书院」：
		1. 【视角一：旅行】如果`与孩子一起旅行`，那么`去书院边玩边学`。 实现效果：既培养孩子学习兴趣，又帮助山区孩子读书。
		2. 【视角二：发掘孩子兴趣】如果`孩子对学习不感兴趣`，那么`带孩子去书院发掘对自然科学、人文的兴趣`。实现效果：实现效果：既培养孩子学习兴趣，又帮助山区孩子读书。
		3. 【视角三：关注孩子教育】如果`对儿童教育感兴趣`，那么`带孩子去书院借鉴创新教育，参加父母课堂`。实现效果：既学习育儿理念，又帮助山区孩子读书。
		4. 【视角四：关注公益教育】如果`热衷公益和儿童教育`，那么`（带孩子）去童行书院支教`。实现效果：既长时间帮助山区孩子，又能满足较好的生活需要。


以上四个视角相互较为独立，建议我们的故事最多2个视角。

---------

查询「多背一公斤」的介绍，其中有这么一条：


>建议
公益其次
不要喧宾夺主。“多背一公斤”是旅途中的举手之劳，能做固然有收获，不做亦无伤大雅。不必将公益作为旅游的目的，这样反而会产生不切实际的期望。

自己的故事，总是想到一半就被推翻。先把暂时的思考列出来，希望启发大家思路。

**Comment by gabriel-guobin** [comment]
顺便把刚才整理的 爱银发视频中 部分文字部分贴出来，供大家参考。
借鉴另一种讲故事的方式


## 时光攻防战 （文字摘录）
* [爱银发宣传片：时光攻防战 | Mind +](http://mp.weixin.qq.com/s?__biz=MzA3Mjk0MTcyNg==&mid=205509837&idx=1&sn=b365cc8bf322c90c88fa316b830733ba#rd)

**一群心智黑客**  
怎么借助认知科学与大数据  
**抢回被遗忘的时光**  
  
  
失智症是一种残忍的疾病  
（失智症又名老年痴呆症）  
  
  
长辈离世，三分之一与失智症相关  
（棺材动画效果）  
  
它让你丢失了 儿女的样貌  
也丢失了 毕生所长  
（碎片化消失，动画效果，下方留白）  
  
  
（接上页留白空间， 上方留白）  
它让你丢失了 另一半的名字  
也丢失了 路的方向  

  
  
而你可知道，失智病程如此漫长  (动画：从1年到10年）
- 知能减退
    - 生活功能障碍
        - 行为及精神问题
            - 安养照顾机构
                - 死亡「灰色」 

  
疾病前期  
- 记忆没有丢失  
- 认识照料的人  
- 此时治疗效果好  
  
疾病后期  
 - 记忆已经丢失
 - 已经认不出照料的人
 - 治疗效果差

我们对它毫无察觉，却错过照料长辈的黄金时间
  
**怎么借助认知科学与大数据**
帮助正在老去的爸爸妈妈
**抢回被遗忘的时光？**

安人心智团队及优势介绍….

**Comment by oliviayx** [comment]
【童行书院】切入点应该是童行，儿童旅行，从旅行中获得一些在日常生活得不到的，用优质的项目对儿童进行职业引导、培养兴趣，接触更多的人文和自然，但是这样的旅行是不是就是夏/冬令营？如果是，那么和别的夏/冬令营比较优势在哪里？帮助山区的小朋友对消费的父母来说有什么吸引力。
从旅行的角度是我比较倾向的，在同时培养的孩子的兴趣，顺带可以帮助山区小朋友。郝景芳老师对于这个项目提到了要可持续，只有有足够的资金才能可持续，不依赖于其他企业，所以首先还是要能够吸引到消费者。

**Comment by xiashuang613** [comment]
梳理童行书院关联人物，明确下来是包括四个方面：城市儿童、乡村儿童，城市大人（所谓的支教老师、城市家长/父母），乡村大人（乡村儿童父母，村落村民）。从一个项目角度看，童行书院的故事讲起来就容易陷入把所有关联人凑在一起的“大杂烩”。尝试把四个关联人，两两组合，分别写作故事，降低难度，清晰表达。粗略勾画：

- **故事一：城市儿童&乡村儿童**

城市孩子：熟读所有与星空、自然相关的诗歌，但从来没有见识过真正的自然图景，询问大人“XXXX”（某句诗）是什么样的，大人无法回答；
乡村孩子：与之相反，日夜所见熟悉的自然图景，却因为缺乏阅读无法获得更高表达词汇（比如古诗）；
童行书院的项目将两者牵连。

想法：有首诗“一个孩子向前走去，他看见最初的东西，这些东西就会成为他的一部分”（不确定原话，意思如此）与此呼应；因 为孩子读诗 的诗歌影响。


- **故事二：城市大人&儿童（城市+乡村）**

城市大人：原来是一名教师，或者是一名博物馆工作人员或者研究者，常常在城市不同场所与孩子分享陈列的文物/植物/动物，如数家珍，
转折：没有身处真实自然，有一天一个城市孩子问起稻花香，他词穷（或者，为寻找快乐，他旅行中感受真实的自然，稻花香后听稻浪，希望带给更多城市孩子）
转机：童行书院招募，参与招募。
最后：带着城市孩子前往乡村，真实情景的行走，乡村儿童获得其教授机会；

想法：城市大人的身份设置，是要有一定能力的，不是随随便便的一个人去乡村就支教而已，能够吸引城市儿童去参加童行书院，一定要真实有料。

- **故事三：乡村大人&城市儿童**

乡村大人：设定村落老人，有一技法（哪怕种菜、古法卤豆腐之类），不过在与孙辈日日相对，人丁稀少，生活热情不高
转机：童行书院落地，寻找当地村民参与，提供儿童户外行走支持，老人参加，获得首肯，得到回馈
最后：乡村孩子获得有趣好玩的书以及参与活动，城市儿童在其学到某种技能，或者了解某个技法等等；村落繁兴。

想法：一直想以村落的未来出发，这样的项目落地，受益的是村落的未来之境，在这里没有思考透，大致如此。

- **故事四：城市大人&乡村大人**

城市大人：爷爷/奶奶级别，因为没办法解答孙儿五谷、花海之类的问题（小时候在大自然长大，长大后进城远离自然）
转折：因菜市场买菜，送了旅行优惠名额，参加了童行书院的活动，在乡村找到曾经的小伙伴，
最后：回到童年现场，白天带着孙辈参与自然活动，夜晚读诗
想法：**带童年回家** 激发的一个点，并不完善，老人和孩子，是我觉得最有情感共鸣的，但光说孩子不行，孩子最终都成为老人，老人都曾经是小孩。

以上几个小故事，都是简单的勾勒。最小故事写作，之后也可以串联成一个大故事。在以上四个组合创作故事，童行书院的出现都是在转折，虽然都是起到突出作用，但也有生硬之嫌。在下一步，可以进行更优化的组合。
欢迎讨论。

**Comment by gabriel-guobin** [comment]
### 反思一下，自己为何编不出满意的故事？
- 用并不熟练的高阶算法，尝试去生成故事，忽视了 「自主心智」 和 「大脑默认网络」。

询问了夏霜同学的故事构思，这种远距联想方式，很受启发，与大家分享。  
没来得及征求 @xiashuang613 的意见，希望不要介意！

以下为聊天记录摘要

------

夏霜 23:15
所以傍晚没办法给您发图，原因在这个草图基础上，列了四个故事框架

![d](http://upload-images.jianshu.io/upload_images/3703151-39153c55c06a7a3d.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

Gabriel 23:15
打死我也没办法根据你这张图复原出这四个故事

夏霜 23:17
可能是我比较熟悉乡村和城市吧  
行走在乡村与城市间，两者的美与缺憾，可以相互弥补。  
吸引更多人去当地，并不能只靠着公益二字，公益情怀终究会被消耗掉，随着当地发展得越来越好的时候。  

Gabriel 23:22
我看得素材越多，就越陷到这个思维跳不出来
一直尝试用woop和创新算法的逻辑去套故事，最后走进死胡同，反而写不出故事了。

夏霜 23:25
有时候我觉得认知写作学习 背后 是人 

Gabriel 23:25
犯了忽视 自主心智 和 默认网络模式的错误

夏霜 23:30
我不赞成捐赠人捐钱动机就是当地看得见的贫困。这样的参与动机，最后结果是捐赠人一时满足，但无法改变长远的贫困，受助人安图于贫困带来的不劳而获。永远没办法改变。所以在一开始的设定里，我不想写当地经济如何差如何落后。

Gabriel 23:34
尤其喜欢第三个村落老人的

夏霜 23:39
这是我第一时间想到的。昨天你问我以谁口吻讲述故事，我的回答就是老人
我对老人有天然的情感在

Gabriel 23:47
老人这个角色我们都没想到，其实一直以来都被低估了。社会发展太快，大家只向前，没来得及回头。其实老人一直都是民族的集体潜意识中很重要的角色。

**Comment by 54elim** [comment]
今天听了线上答疑后，有个小故事，看看是否可行：
-**主人公**：A，年轻设计师。
-**这里/这时**：他刚获得业界新人奖
-**那里/那时**：他来自山区，从小喜欢画画。他有个梦想，成为画家。但人们告诉他这是不可能的，画画是有钱人玩的，穷人的孩子老老实实地打工赚钱就好了。
但是他还是不停地在各种地方画画。
后来，他画画被一个外地人发现了，这个人就是“童行书院”的老师（艺术家），带他进入了书院。
他们教会了他识别美、创造美，让他相信农村的孩子也可以学习艺术。
-**这里/这时**：现在他成为了一名设计师。下周他就将再次回到书院，以一名支教老师的身份。

反转：农村的孩子跟设计、艺术是无关的，他们缺乏这方面的训练

**Comment by oliviayx** [comment]
总结一些昨天和大家聊天受到的启发
我们的切入点和重点应该是教育，但比教育多一点公益，这种方式可以减小认知负荷。
根据阳老师答疑提出的，故事要有反转，站在人性的角度，那么我们选择的人性可以是勇气，反转可以选择女童、农村孩子帮助城市孩子。。
采用 @xiashuang613 提出的故事一：城市儿童&乡村儿童
最小故事：
事件一：城市儿童A有心理问题，农村儿童B没有钱念书
事件二：A,B均进入了书院
事件三：A的心理问题治愈，B获得了良好的教育，最终事业成功家庭幸福。

这个故事很俗套，如何吸引注意力可以从以下三个方面入手：

1. 进入书院后，乡村儿童B帮助城市儿童A更多（常识是乡村儿童是获得帮助的人）。

2. 强化女童的特殊性

3. 故事叙述的顺序：先说A在年幼时的心理问题和B在年幼时的经济问题，再说多年后她们都事业有成，这是两条分开的线索，让观众以为她们不认识，当她们参加书院校友会时相遇，她们相识这件事也是一个惊奇点。同时时会引起一个疑问，她们为什么年幼时不顺，成年后却幸福，中间发生了什么，顺利成章就可以说她们都加入了书院，在书院里发生了什么。

**Comment by 2Forest** [comment]
阳老师意见：

1.童行书院项目经创始人周密考虑，模式已经比较成熟。建议避开“童行书院”的名称，但模式不涉及版权，可以借鉴。
2.项目名称建议：可以叫某某学社，可从古诗词中寻找笔画简单的字。
3. 在答疑中提到性别是不可改变的固化属性，我问是否可以缩小范围至女童，阳老师说这个角度很好，最后也许可以做成一个真的项目，必要的时候他可以请他做公益的朋友进行指导。

在课后讨论时发现女童项目的话角度和着重点不太好掌握。小伙伴建议做更多调查后再决定，原项目也继续构思最小故事。

以下是非学术搜索引擎式调查，先给大家借鉴。

女童方向：

1. 农村重男轻女思想是否会导致留守女童比留守男童多？
答：没有找到最新数据，在2011年一篇文章中说，“在全部农村留守儿童中，男孩占53.71%，女孩占46.29%，男女性别比为114:75。”女童比例小于男童，有点意外。

2. 据2015年11月发布的《中国中西部农村留守女童生存发展报告》。

目前，我国民间组织介入农村留守儿童服务的力量极其有限。这一方面与缺乏对留守儿童问题以及需求的准确把握相关，另一方面也与留守儿童问题的复杂性以及民间组织资源的局限性有关。

报告建议……加快政府购买民间组织服务的政策探索。

民间组织在介入帮助的过程中，应该特别注重服务项目设计的专门化和专业化，避免同一区域内资源的重复投入。

3. 2017年3月，中国社会福利基金会爱小丫基金在北京召开新闻发布会，发布《中国农村留守女童生存发展报告·2016》（以下简称“《2016粉皮书》”），并与女童保护基金、红伞基金等十数家相关爱心机构共同发起“关爱女童联盟”。本报告相关报道中没有有用的数据。如果有意向这个方向设计项目，可以进一步探寻。

留守儿童方面：

1. 全国妇联2013年研究报告显示，我国农村留守儿童至少有6102.55万人，超全国儿童总数的五分之一。

2. 民政部、教育部、公安部截至2016年7月底在全国范围内开展一次农村留守儿童摸底排查工作，建立农村留守儿童信息库。但该信息库有关的新闻都在2016年，并没有建成后的更新。

3. 公益机构有“上学路上”等。

我试试尽量找一下相关的报告，讨论时有小伙伴说数据其实并不太能打动人，最重要的是最小故事，但是我发现自己编故事的能力实在太差。所以先试着找找数据看看。

还有，我有印象的好的公益小短片中泰国小故事有好几个，大家也许可以从中得到点灵感，我的灵感还在路上：）

**Comment by gabriel-guobin** [comment]
## 项目思路梳理（结合周末答疑和微信中分享的资料）

### 选品牌名称
  - 主题：跟旅游、儿童相关
  - 文化模因：基于天上有行云，人在行云里这样优美的诗句去找出一个品牌的词汇
   - 认知负荷：
     - 好写：笔画要比较简单
     - 好记：元音 ( AEIOU ) 比例要大于60%
	 （儿童相关的项目，元音比例足够大，小朋友和家人才记得住。）
  - 最小行动：动宾结构，突出最小行动，如「多背一公斤」，「陪孩子读诗」
  
### 构建最小故事
1. **角度一： 教育**
  - 举例：二期子午鸟同学关于「一土学校」的点子
  - 传统思维：我去了这个学校会怎么怎么样（反复的在讲他为什么好，我要说服你来）
  - 时空变形：从学校毕业，然后怎么怎么样，使得这边的小朋友变得更自信，更怎么样.（完全扔开前面，直接从最后面切入）

2. **角度二：旅游**

  1. **失败案例**：氢气球（纯银）、蝉游记（纯银）、妙计旅游。  

      对最小故事的推演与真实商业社会的推演存在强关联。最小故事逻辑不对，必然会导致问题。二期和三期的小伙伴应该对此案例印象很深刻。
    - 相关链接：

      * [氢气球旅行 App 的使用体验如何？ - 知乎](https://www.zhihu.com/question/37419717)

      - [创业三年，他瘦掉25斤并裁掉一半员工-虎嗅网](https://www.huxiu.com/article/188618.html)

   - 阳老提出的问题：旅游产品为什么容易出问题？

     - 我的思考：以纯银的两款旅游攻略分享产品为例，用户的认知负荷较大，需要在旅行中消耗过多心力去完成记录或分享的过程。难以实现最小行动。所以不利于用户习惯的培养。（仅是片面思考，有待验证）
   
  2. **好的案例**，如「多背一公斤」,利用时间差，和空间差。现在要反过来进行新的逆转。
  3. **最小故事点评**
   - 初版故事：角色交换太浅，但是可以顺次思路去想，得到新的体会。甚至可能发现完全和童行书院模式不一样啦。

   - 夏霜的第三个故事：阳老看完后，想到对人性把握的不够，个例不太能唤起集体潜意识。所有的故事最终要回到人性上去。

   - 爱文的故事：假设人性词汇是 勇敢。 小孩子都是弱小的，一个乡村，改造成一个生态链，关卡设计，原本是当地的一批，构建成新的世界。交到新的朋友，邀请他来城里玩。

### 改进的想法

#### **思考**：
  - 怎样将故事带入人性的思考，利用时空变形，进行逆转？
   
#### **启发**：
   
1. 从CH4中的人性词汇表中选择合适的**人性词汇** ，作为故事的正面和反面，唤起冲突。
	  - 打破刻板印象，带来惊奇
	  
2. 故事可以**从后往前讲**：逆向利用时空的模式识别，空间置换，时间穿插，时空混合(利用错误记忆范式描写氛围)
	
3. **乡村的教育模式**
	可设定为（突破层层关卡的体验式挑战）。通过完成挑战的过程实现预设人性的逆转。题材与文化艺术相关。参考记忆生存优势词汇![记忆的生存优势效应](http://openmindclub.qiniudn.com/cnfeat/image/OMW3w402.jpg)
	
	- **音乐**：侗族侗歌
		
	- **文字**：东巴文  [达祖小学夏令营](http://mp.weixin.qq.com/s?__biz=MzI4ODAwNjIwNw==&mid=2652495359&idx=1&sn=b26890102c725fd6a3a2914bb80a5e1e&chksm=f02874afc75ffdb9bec108eeda144c9f4aeb82e93972d54b793e0e51574cd1d5a82c64c99f57&mpshare=1&scene=1&srcid=0417N97nNd8Wd6oRERBTlC0y#rd)
		
	- **诗歌**： [船是中国人走向世界的图腾](http://mp.weixin.qq.com/s?__biz=MzI3NjE3ODEzNw==&mid=2649025607&idx=1&sn=10684c7ddfb01289c64e32c1ff294274&chksm=f36939f1c41eb0e73419f4fd772d43cb895f23772f13b7deec970f0919d1652dbd2a6e62688d&mpshare=1&scene=1&srcid=0415f5U5bWEDKr2hHvGQUGNh#rd)
		
	- **自然**： [矗立在云与山之间，他们打造藏地第一所森林学校，带嘉绒孩子找回与土地的连接](http://mp.weixin.qq.com/s?__biz=MzA3MjExMDEzMw==&mid=2650398021&idx=1&sn=8fba292fb6d2e07f94868f52c44acf9f&chksm=872e241fb059ad09fbd4b1da5f45b56fbf836bb27585d4b1d942b9d41296efe4ea46df6fa675&mpshare=1&scene=1&srcid=1124szwelE9EjvJT0LaG1Ggs#rd)
		
	- **饮食**：[腊月村的水磨](http://mp.weixin.qq.com/s?__biz=MzA3NjAwOTEyMg==&mid=400144545&idx=1&sn=ec8c698d8a561c3d4941813cb18fa014&mpshare=1&scene=1&srcid=1124i2HuvlPnePVfo5ak27YZ#rd)
		
4.**缩小范围**（提升情感指数：对读者品味作出评价，挑选合适的读者）

  - 仅关注城市孩子教育（不过多渲染公益要达到的效果）
	
  - 仅关注留守儿童（歌路营2015年报、 [留守儿童教育刻板印象威胁探讨](http://www.baywatch.cn/jiaoyulunwen/liushouertonglunwen/65421.html)）、《中国留守儿童心灵状况白皮书（2015）》、【REAP洞见】母亲外出务工对0-3岁婴幼儿发展的影响？
	
  - 仅关注女童（探讨中）
	
  - 仅关注信息收集与分享（建立各个乡村公益学校的信息聚合平台）让更多人知道这些学校。
	- 规划家长出行信息和学校特色参考。
    - 志愿者和乡村学校间理念学习与交流的平台。

#### 疑问：关于倒叙故事的手法，暂时还没想通，有些疑问？
- 如果按照倒叙，先展示孩子毕业后或长大后的成就，再回到过去讲述当年在学校的故事，是否对于公益项目不太合适？
- 在结业视频中应如何展现这个故事？
- 是否有类似的可参考的案例？
