### ISSUE TITLE
ch9 文案汇总提交 & 最后两天时间安排

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#21]
### 目前BP方案不足
三个段落之间联系不够紧密。整体的BP缺乏故事性。

### 改善的方案

- 整体结构还是三段 「我带你去（地点），我带你做（事件），我是谁（过去，现在）」。
- 但是纵向，以[人物]联系起来，按照人物的特点分别展开（可以暂时设置两个人物：画家和编剧）。

### 文案提交和定稿时间

- **文案提交时间**：周五 晚上 24:00  请大家将最新版的文案提交在本issue。（所有人）

- **文案初稿时间**：周六 早上4：00 前 第一版发出issue，大家异步点评。（郭斌、夏霜、璞童）

- **初稿沟通会**：周六 上午 7: 00~8：00  zoom会议。大家交流提出修改意见。（所有人）

- **Keynote初稿/文案第二稿**：周六 晚上 20 : 00  前  发出第一版。大家异步点评。（行之、珞洛、郭斌）

- **Keynote第二版/文案定稿**：周日 6:00 （bravo润色检查，利用下时差哈）发出链接

- Keynote定稿沟通会

- 发给教练或其他外援提出最后的修改建议：周日12:00发出

- 最终版：周日晚上20:00前发出，之后只做微调。

（Keynote 存放地址，建议百度网盘）

----

### 几个问题的想法

1.  **关于@bravo 的想法**
>串起来三个部分的是“老师”这个身份，三个部分分别对应旅游、教育、公益
**第一部分：旅游**
我带你去...
写童行书院三个地方的景色
**第二部分：教育**
不同场景下可以开展什么活动、课程，最好是三个场景
**第三部分：公益**
老师自己的故事
三个老师，**画家、编剧、自然老师**
前两个部分，老师都只是一个虚拟的“引导者”、“带领者”身份，只有最后一个部分把老师具象化了，这是我目前认为合理的逻辑。

我个人认为非常准确，可以说「旅游、教育、公益」是暗线，明线则是"老师"带我们探索的这个故事。

2. **关于第一段与第二段的衔接**
在写的过程中，发现第一段与第二段如果分割过于明显，比如：
```
场景一，场景二   
场景一中的活动，场景二中的活动
```
可能会造成清单式的感觉。  

建议可以尝试，将第一段与第二段合并，比如：
```
场景一：场景中的活动
场景二：场景中的活动
```
这样的方式来写。

3. **关于以一个身份贯穿，最后交代团队背景。还是穿插几个身份一起讲故事。**

目前没有看到效果不好去评判，所以等大家完成后，凭借成最终版本再做决定。

4. **关于「教师的身份」是在开头介绍，还是在最后「我的故事」时介绍？**

目前我个人还是倾向于最后介绍，因为试着在开头写的时候，总感觉很罗嗦，进入正题较慢。  
如果大家能用很剪短的语言在开头提一下。我觉得效果也会很好。当然，这部分顺序，后期调整也比较容易，所以大家按照自己认为合适的方式写就可以。

**Comment by 2Forest** [comment]
The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.
——马赛尔·普鲁斯特（Marcel Proust)《追忆似水年华》

我带你去山间，
但不是为了让你去逃避；
我带你去草原，
但不是为了让你去放逐；
我带你去与其他民族同胞相见，
但不是为了让你忘记自己。


在山间的溪湖旁，
你可能会看到自己荡漾在水面的倒影，
但你不只会看到这些。
你也许会了解溪旁的野花野草怎样自成一个世界，
迷失在花草纪年里。
在草原的空旷中，
你可能会驱马驰骋或牵马游走，
但你不会只做这些。
你也许会亲自点起篝火，
就像亲自在历史的绵延中点起一支火把；
在其他民族的故乡，
你可能会循着他们的古法印出同样精彩的神秘图案；
但你不会只创造这些。
你也许会听着他们的传说，
做出你独特的一版图释，
在别人的故事里，
发现另一个可能的自己。

我是谁？
你为什么要跟我走？

我可能是曾经的编剧，
也可能是曾经的画家,
…
但是现在，我只有一种身份，
我是童行书院的老师。
我在这里等你，
等着带你发现风景中少有人探索的玄妙，
等着陪你遇见从来没见过的自己。

童行，
期待借你一双眼睛，
与你、与你家宝贝，
一起同行。

下面是如果加字幕的话，童行书院的介绍。大家可以看情况再修订，我是从微信等文章中整理的。

“童行书院是一家由雨果奖获得者郝景芳发起的社会企业。

童行书院会与在风景优美的贫困地区设立驻点，在度假村建立图书馆与课堂，派老师长期驻扎。书院的老师有两种职能，旅行教育和公益教育。旺季做旅行教育，获得收入，支持淡季的公益教育。

童行老师在北京总部经过几个月的培训，可以提供一系列在大自然环境中的教育课程，包括自然博物、户外、美术、天文、戏剧、故事创作等。这些课程可以给旅行者家庭，也可以免费提供给当地孩子。”



这段是从晴妈说里节选的，大家参考：
有了内心的感觉，有了自发的创造，就好比写下了最初的1，此后的所有学习提升都是后面的0。1000000000。心中有光，就能组合一切碎片。如果没有这个1，那么学再多碎片知识都只觉得无味、无用。

**Comment by 2Forest** [comment]
写的时候发现没办法用一种身份，比如编剧，去带几个场景。大家有同样的问题吗？

---
guobin: 这个没关系，后期我和@夏霜 再从大家的故事中挖掘！

**Comment by oliviayx** [comment]
我曾是博物学家  
也曾是大学老师   

我想带你去桃花源  
![](http://i.imgur.com/RJgRGZA.jpg)    
在溪水中洗涤心上的灰尘   
![](http://i.imgur.com/nHOMfoP.jpg)   
探访阡陌交通  
![](http://i.imgur.com/GdeevXP.jpg)    
在田园悠然牧歌  
![](http://i.imgur.com/4MITSPQ.jpg)    
带着孩子跳水沟  
起跑 跳 着陆    
落入溪水   
衣服湿了有什么关系    
![](http://i.imgur.com/qSLn5TN.png)      
把乡愁留在楼纳  
![](http://i.imgur.com/dKSzMPC.jpg)  



  
我想带你去跳花圣地  
沐浴日月光华   
看第一缕阳光苦苦追寻你  
![](http://i.imgur.com/hACNlwL.jpg)  
拿三棱镜变出彩虹  
![](http://i.imgur.com/2rk5Cpn.jpg) 
让孩子把玩  
![](http://i.imgur.com/GE24paf.jpg)   
看金星走在天际，画下一颗五芒星  
握着孩子的手指画出低空闪耀的南十字  
月光悠悠，晒过寒武纪  
![](http://i.imgur.com/FGVjoUZ.jpg) 
  
![](http://i.imgur.com/peWe1MB.png)
  
![](http://i.imgur.com/kkFkJeb.jpg)

我想带你去冬奥之城  
等候骤雪初霁 
![](http://i.imgur.com/78Qpael.jpg) 
 
让孩子在放大镜下看  
![](http://i.imgur.com/1ZGrmhW.jpg) 
 
分辨雪花的不同形状  
![](http://i.imgur.com/bK550XD.jpg)    

在雪场寻找一只傻狍子  
![](http://i.imgur.com/CO35Y2q.jpg)  
我们一起炸开它的尾巴  
![](http://i.imgur.com/g8HCcas.jpg)  



我想让你睁开双眼 打开心窗  探索自然
亲近自然 认识自然    
但感知远比认知更重要

无论我曾经有多少种身份
但现在，我只有一种身份  
我是童行书院的老师  
我在这里等你  
等待与你和你的孩子同行  


童行书院  
与你同行  
与你童行

**Comment by gabriel-guobin** [comment]
## 开篇
你是否在寻找一段旅行
带孩子出发
用全新的视角看世界


## 场景一 

我带你去星空下，
穿过格凸河头顶的一线天，感受浩瀚宇宙
![](http://ww3.sinaimg.cn/large/612e1834gw1fb5fwvvegjg20cc06y7wj.gif)

>孩子们追问着星星的名字，

>而我更愿分享的

>是那遥远的未解之谜，等待将来自己去探索

>我用天文望远镜带孩子们捕捉星星的笑脸，

>然后熄灭篝火，围坐在星空下，听他们讲述自己的故事。。。


还可以拍摄漫天的星轨，带孩子穿越回梵高画布中的《星夜》，感受时间与空间的对话
![](https://cloud.githubusercontent.com/assets/22133106/25992018/e1abebc0-3737-11e7-9464-28a48d661d02.jpg)


感受一个画家对万物的情感
>当我画一个太阳，我希望人们感觉它在以惊人的速度旋转，正在发出骇人的光热巨浪。当我画一片麦田，我希望人们感觉到麦子正朝着它们最后的成熟和绽放努力。当我画一棵苹果树，我希望人们能感觉到苹果里面的果汁正把苹果皮撑开，果核中的种子正在为结出果实奋进。当我画一个男人，我就要画出他滔滔的一生。如果生活中不再有某种无限的、深刻的、真实的东西，我将不再眷恋人间。
——《亲爱的提奥》文森特·梵高
![](https://camo.githubusercontent.com/43114826284c19952326650f58bbb015b92e2a38/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f652f65612f56616e5f476f67685f2d5f5374617272795f4e696768745f2d5f476f6f676c655f4172745f50726f6a6563742e6a70672f37353770782d56616e5f476f67685f2d5f5374617272795f4e696768745f2d5f476f6f676c655f4172745f50726f6a6563742e6a7067)

## 场景二

我带你去雪山上  

![default](https://cloud.githubusercontent.com/assets/22133106/26005177/db84b348-376a-11e7-848b-71a206820523.jpg)

打雪仗、拉雪橇，把厚厚的积雪堆成孩子想象的形状
（此处图还没找好）


然后一起欣赏雪花的模样

![](https://camo.githubusercontent.com/657567fefc4013354069f5629d77303aff94490a/687474703a2f2f7777772e6e617467656f6d656469612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30342f2545392539422541412545382538412542312545372542352539302545362539392542362e6a7067)

以及，另一个很美的名字——「来自天空的信使」

>日本物理学家中谷宇吉郎博士曾把雪比做“来自天空的信使”，并查明千差万别的雪的结晶形式取决于高空气温高低和水蒸气的多少。

* [显微镜下的雪花真漂亮](http://news.xinhuanet.com/forum/2005-01/30/content_2519823.htm)
（上面链接里的图片需要合并成一幅图）


小溪旁，雪花翩翩飞扬，你带着孩子随着雪花跳舞，  

我为你们朗诵 徐志摩《雪花的快乐》

![](http://ipsm.hner.cn/xxpd/tjxx/shang/kx/4/05/8/8_1/8_1_mt/image/tkx4s080128031.jpg)

* [徐志摩-雪花的快乐 (赏析)](http://www.artsdome.com/books/xzm/003.htm)

>假如我是一朵雪花，
    翩翩的在半空里潇洒，
    　我一定认清我的方向——
    　飞扬，飞扬，飞扬，——
    这地面上有我的方向。
    不去那冷寞的幽谷，
    不去那凄清的山麓，
    　也不上荒街去惆怅——
    　飞扬，飞扬，飞扬，——
    你看，我有我的方向！
    在半空里娟娟的飞舞，
    认明了那清幽的住处，
    　等着她来花园里探望——
    　飞扬，飞扬，飞扬，——
    啊，她身上有朱砂梅的清香！
    　那时我凭借我的身轻，
    盈盈的，沾住了她的衣襟，
    　贴近她柔波似的心胸——
    　消溶，消溶，消溶——
    溶入了她柔波似的心胸！    

## 场景三 

我带你走进「桃花源」
（此处要是有那个洞口的照片就好了）


![default](https://cloud.githubusercontent.com/assets/22133106/26005152/cd34157c-376a-11e7-8d75-b5ad424ea5c0.jpg)



任孩子在油菜花海撒野

![default](https://cloud.githubusercontent.com/assets/22133106/26005686/713fc91c-376c-11e7-892f-82760bff315e.jpg)
（图片需备注来源）

用作品描绘出心中「楼纳」的颜色
![default](https://cloud.githubusercontent.com/assets/22133106/26005772/ad3bb336-376c-11e7-97a2-e99151992553.jpg)


再到小溪旁，孩子们与布依族姑娘 一起印染
![](https://camo.githubusercontent.com/10eb90dd654898e2fedbd887c586d302ea1a8b0d/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f343035333839312d346462613066666264343939336636612e6a70673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

[马蓝草浸上蓝，
蜡液封住白，
印下星辰、田地与河流]
![](https://camo.githubusercontent.com/42817280fd9877b474f70736fa8add68ec74ed29/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f343035333839312d383462386530653536313664363066352e6a70673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

你可以趁机放松自己，随我来到露营竹屋，品当地美酒，饮嫩绿鲜茶。

![](https://github.com/gabriel-guobin/ChildAcademy/blob/master/ch9/%E6%A5%BC%E7%BA%B3%E7%81%AF%E7%81%AB%E5%B0%8F%E5%B1%8B.png?raw=true)
（图片需备注来源，“首届楼纳国际高校建造设计大赛”获奖作品）

## 我的故事 (更改的版本）

你遇到的我，   

也许是曾在梵高的星空下痴迷的美术工作者，在寻找最本真的艺术。
(对应场景一）

也可能是赋予雪花生命的科幻编剧，想创造和生命联结的故事。
（对应场景二）

还可能是用建筑将音乐凝固的设计师，期待用自然原本的语言与土地对话。
（对应场景三，但是活动和人物身份略有不太贴切，还需修改）

对乡村的热爱和创新教育的思考，把我们聚集。

现在，我们共同的身份是「童行书院」的驻地教师，

打造以儿童为中心的创造力教育。

让旅行的孩子感受自然，爱上自我探索和创造。

并长期免费对山区孩子进行教育及创造力课程的培养。

或许有趣的灵魂终将找到彼此，希望与你携手同行。

**Comment by windflyinglx** [comment]
额，先按照要求提交一个版本。以及不好意思没找图。
我带你去看桃源楼纳
让青青的寨子浸浥你干燥的心 
背倚巍巍青山
足踏潺潺溪水
在吊脚楼上与清风窃窃低语
于阡陌之中同阳光耳鬓厮磨	

我带你仰望璀璨星空
观猎户金牛殊死搏斗
看牛郎织女隔河相望
我带你观摩东巴蜡染
蜡刀为金丝绒捎来熔蜡的不舍
十浸百染 千沸万煮
终于在蜡的冰纹和分色中镌刻它们隽永的爱恋

我曾是一名画家
现在，我是童行书院的老师
来为你拉开天地的幕帘
扶着你的手
引导你在自己的心上画下那惊鸿一笔
即便有一天你离开童行
数年之后，我依然能在人群中辨认出你的模样
那眼中的星光
那眉间的轩昂
那发现一片广阔天地的惊喜样貌
一如你当年落笔之时的生气勃勃

**Comment by windflyinglx** [comment]
额，然后，写完上面那个版本后，我仔细看了下昨天bp点评会上各位教练和阳老学徒给我们项目提的建议，梳理如下：
1. 像是罗列，不像故事，没有起伏，没有逆转。
2. 可参考的思路和建议：
	- 对比：没有童行书院之前的场景，很没有意义的旅游；童行书院的旅游，看到完全不一样的东西
	- 不要多条线索，一个主要人物引导引导就够了。一个导师指引，深入植入故事里。在介绍背景时，介绍多个老师就行
	- 描述具体活动：具体的活动有什么新奇的设计，可以展开，更可以让别人理解这个课程的价值。
	- 价值观：不光要有知识，对孩子价值观的影响也可带出来；痛点和家长需求可以紧密结合，相当于是深度游，而不是走马观花

我们现在的bp思路，和昨天点评会之前的差不多，依然没有明显的故事，感觉有点儿……像在往枪口上撞……
现在的诗化语言确实很美，而这似乎有点儿妨碍讲故事……（我第一次看那个视频就差点儿睡着……）

之后我又看了一下手册里的往期项目，确实没有一个是这样罗列式的。就算再简单，如不到两分钟的红色，也是有故事逆转和起伏的。
额，感觉我们有些危险……

然后我试着憋了一个故事出来，还是用到了“我带你去……”的结构，把诗化的语言进行了一些调整。
因为时间紧迫，不知道最后定稿的bp会是啥样。只是感觉教练们已经明确提出前方有坑慢行了，就这样冲过去似乎不大好……（不知道周三提交的组周一周二还可以改吗？）
目前我们这个诗化的思路，应用到的主要是文采，而对于认知写作学的三难的另外两难 逻辑和故事，涉及不多。写出优美的散文诗，很多人不上这课也能挥洒自如，可是要在项目中设法展现三难，除课程学员外，大概实属罕见。所以，我们要不要尝试着尽量多地展现一下认知写作学学员的风采？

这故事纯属抛砖引玉。

A：我不喜欢旅游。
粑粑麻麻每次带我出去玩，无非就是下车拍照，上车睡觉，吃吃喝喝，玩玩买买，一路走马观花，火急火燎地赶场，比上课还累。
三个月前我刚去过陕西西安，但现在，除了羊肉泡馍擀面皮，我几乎不记得什么了。兵马俑？大雁塔？华清池？也只有从照片上才能确认我去过。
旅游，真没意思。

B：我最喜欢旅行了。
在桃花源的阳光里奔跑
在吊脚楼上与清风私语
背倚巍巍青山
足踏潺潺溪水
旅行，让我重归自由。

A：咦？这听起来跟我的旅游很不一样啊？
B：嘿嘿，那当然！我肯定能让你大开眼界！
A：切，吹牛，能有什么不一样？（将信将疑）

B：我会带你仰望璀璨星空
观猎户金牛殊死搏斗
看牛郎织女隔河相望
A：真的吗？我特别想认识天上的星星！

B：我会带你观摩东巴蜡染
蜡刀为金丝绒捎来熔蜡的不舍
十浸百染 千沸万煮
终于在蜡的冰纹和分色中镌刻它们隽永的爱恋
A：好想亲眼看看那么漂亮的蜡染是怎么一刀刀刻上去的！

B：我还会让行业专家对你陪同指导，锻炼你解决项目问题。
A：这也太酷了吧？
B：我还会为你精心设计专业体验，引导你自主创作。
A：……等等，你到底是谁啊？
B：我是童行书院，我（以下省略童行书院介绍30字）
我在楼纳，在XX，在XX，来找我，让我带你一起去探索星空大海。

好了，要说的话说完了，我安心去睡觉了。

**Comment by xiashuang613** [comment]
行之提到的“像是罗列，不像故事，没有起伏，没有逆转。”这也是我一整晚纠结的地方，罗列，如何讲述故事；故事如何，打破罗列。不断打破文稿组字，依然找不到刀起刀落的节奏。郭斌和珞洛的，我结合美图，做视角切换，找起承转合的点，又想贴合童行书院，琢磨琢磨琢磨。我明早再看行之的，困顿时刻。

**Comment by gabriel-guobin** [comment]
## 我的故事 (啰嗦的版本）

你遇到的我，   

也许是曾在梵高的星空下痴迷的美术工作者，开过画廊，办过个展，在寻找最本真的艺术。

也可能是赋予雪花生命的科幻编剧，写过小说，拍过电影，想创造和生命联结的故事。

还可能是用建筑将音乐凝固的设计师，厌倦了钢筋水泥，期待用自然原本的语言与土地对话。


（感觉费点心思的话 ，能把这三个人 写成  真、善、美。 不知道这种体现有什么意义，所以就没改）


我们关注创新教育，享受与孩子一起的时光。 

当灵魂识别相似的灵魂时，我们加入了 [ 童行书院 ] 团队。

自然、天文、心理、教育，

精英导师团6个月深度培训，我们成为第一批童行教师。

以儿童为中心的创造力教育。

让旅行的孩子亲近自然，

山里了的孩子看看外面。

或许有趣的灵魂终将找到彼此，希望与你携手同行。


---


## 我的故事 (更改的版本）

你遇到的我，   

也许是曾在梵高的星空下痴迷的美术工作者，在寻找最本真的艺术。
(对应场景一）

也可能是赋予雪花生命的科幻编剧，想创造和生命联结的故事。
（对应场景二）

还可能是用建筑将音乐凝固的设计师，期待用自然原本的语言与土地对话。
（对应场景三，但是活动和人物身份略有不太贴切，还需修改）

对乡村的热爱和创新教育的思考，把我们聚集。

现在，我们共同的身份是「童行书院」的驻地教师，

打造以儿童为中心的创造力教育。

让旅行的孩子感受自然，爱上自我探索和创造。

并长期免费对山区孩子进行教育及创造力课程的培养。

或许有趣的灵魂终将找到彼此，希望与你携手同行。

**Comment by gabriel-guobin** [comment]
考虑用结尾的人物把前面的三个场景穿起来。但却是还是存在教练点评时候的问题。 
建议的修改意见：
1. 开头加入痛点，
2.结尾加入部分公益的升华，
3. 中间的活动场景修正下，更加突出主题。
整体效果会好很多。
