### ISSUE TITLE
ch9 BP draft 待修改

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#22]
BP 讨论的视频和录音文件链接: https://pan.baidu.com/s/1o7OZ0Ky   
密码: mjbk

BP 初版keynote链接: https://pan.baidu.com/s/1i4Aq585 
密码: kd9w

### 0  . 开头需要补充一个痛点再现的场景  
场景要紧扣的核心是，感受比知识更重要。或者城市生活中缺乏对美的感受，无法产生对知识的兴趣

  可参考的文章：
  * 一篇书评 [给孩子一颗终其一生都无法被摧毁的惊奇之心（惊奇之心）书评](https://book.douban.com/review/7434093/)
  * 那本书的全文，我整理到仓库了[《惊奇之心》](https://github.com/gabriel-guobin/ChildAcademy/blob/master/ch8/The%20Sense%20of%20Wonder.md)

### 1
通过百度指数的调研，有亲子游计划的人群，最主要的需求在于寻找目的地、旅游线路，所以用了「你是否在寻找一段旅行」。   

而 「用全新的视角看世界」是希望引起思考：什么是全新的视角？我以前的视角是什么？接下来你将带给我和孩子怎样的视角？   

这一幕文字，其实出自以下这句话：

>**真正的探索之旅并不在于寻找新的风景，而是要有新的眼光。**
>
The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.
——马赛尔·普鲁斯特（Marcel Proust，20世纪法国最伟大的小说家	，《追忆似水年华》作者）

![001](https://cloud.githubusercontent.com/assets/22133106/26035587/b48b8f9e-3901-11e7-8dac-666b000d5692.jpeg)

### 2
三个场景总体结构：
- 我带你去星空下
- 我带你去雪山上
- 我带你走进「桃花源」

希望对应空间上的仰视（星空和画作）、俯视（地上的雪花）和容器隐喻（桃花源-蜂巢-建筑）

三个场景内的活动特点：

- 从大到小
- 具象到抽象
- 美丽的自然风景——细节的观察——产生新感觉

遵循的规则是「引导而非灌输」、「少说教、多分享」、「观察、体验、然后说出你的感受」。这些是从《与孩子共享自然》中找出来的，希望的是从我们对每个场景的设计中，能够体现出来。

（写作班路演的时候，大家未必注意得到，但是关注教育的亲子游家长包括童行书院团队看这个BP时候应该很容易领会）。

![002](https://cloud.githubusercontent.com/assets/22133106/26035591/b48e2c36-3901-11e7-8c8e-59c6b98c7a19.jpeg)
修改建议「在山间的帐篷外，仰望头顶的浩瀚」

### 3

![003](https://cloud.githubusercontent.com/assets/22133106/26035592/b48f9580-3901-11e7-80ea-1d541f28ad4b.jpeg)
修改「看着一眨一眨的星星，孩子们追问着他们的名字」  
说明这里最关键的一句是 **「而我想分享的，是。。。。。」**，  
这句话是想让人意识到一种**对比的关系**。可惜把说教式的语言用叙事方式，很难表达出来。大家可以想想怎样表达更好。

想表达的内容其实来自这段话：

>不必为不知道动植物的名字而感到难为情。名字只是生命或事物本质外在的一个标签而已。正如你的名字无从说明你的本质、容貌和个性，一棵树的内涵远比它的名字和一串相关的事实丰富的多。如果你在一天不同时段，随着光线的变化观察橡树，会更深层地欣赏这棵树。从同的角度观察、感觉——闻闻树皮和树叶，静静的坐在它的伞盖下或枝条上，你就能觉知树上，树周围以及依赖于树生存的各种生命。  
> 当孩子开始于自然有了共鸣，你和孩子的关系就由师生变成了共同探索自然的小伙伴。

### 4

![004](https://cloud.githubusercontent.com/assets/22133106/26035588/b48bed90-3901-11e7-995a-0e8b33b7d9c2.jpeg)
这句文字，似乎与上一段少了过度，显得比较突然。可以试着加一些口语话的字（反正是已对白形式读出来的，不用显示的图片上）

### 5
![005](https://cloud.githubusercontent.com/assets/22133106/26035590/b48dde16-3901-11e7-8843-5c26d1d94f43.jpeg)

### 6

![006](https://cloud.githubusercontent.com/assets/22133106/26035589/b48c2ba2-3901-11e7-98b6-c30d51b705a0.jpeg)
已经删改过，文字还是太长，大家看看读那一段比较合适。

### 7

![007](https://cloud.githubusercontent.com/assets/22133106/26035593/b4b88332-3901-11e7-884b-00ae25ab342f.jpeg)

对这个图片还是不太满意，如果有更有视觉冲击的会更好（当然也不要太夸张，一眼就看着不像中国国内的也不好）

### 8

![008](https://cloud.githubusercontent.com/assets/22133106/26035597/b4bd5560-3901-11e7-86fa-78ac47138c5d.jpeg)

### 9

![009](https://cloud.githubusercontent.com/assets/22133106/26035594/b4ba771e-3901-11e7-8ee3-9fd82d38191e.jpeg)

这里玩大块的雪堆，到观察细小的雪花，文字和场景上过度还是不够自然。大家提下修改建议。

另外，想从这一幕引导出下面雪花是有生命的目前的语言是否合适。

### 10
![010](https://cloud.githubusercontent.com/assets/22133106/26035595/b4baf81a-3901-11e7-8799-0c39fbb8d05b.jpeg)
版面的问题，怎么调整更好  
另外图片还略微不满意

### 11
![011](https://cloud.githubusercontent.com/assets/22133106/26035596/b4bb40f4-3901-11e7-9e80-5515673af4be.jpeg)
### 12
![012](https://cloud.githubusercontent.com/assets/22133106/26035598/b4be96a0-3901-11e7-8068-23a18a1de81d.jpeg)
### 13
![013](https://cloud.githubusercontent.com/assets/22133106/26035599/b4e64768-3901-11e7-9ccb-4d5c2da36e1f.jpeg)

### 14

![014](https://cloud.githubusercontent.com/assets/22133106/26035600/b4e7a504-3901-11e7-8c28-354376383257.jpeg)

图片结构略乱。  
初步的想法是，左边两幅和中间那副先出来，出现文字，惊叹。。。  

然后右面出现让孩子们创造自己的作品，再出现右边图片

当然只是个人建议，听听大家的好想法。

### 15

![015](https://cloud.githubusercontent.com/assets/22133106/26035603/b4eb8cb4-3901-11e7-8850-f2d1b3a2a0a4.jpeg)

这张图的时候背景音乐应该是较为舒缓的节奏。

### 16

接下来的三页，如果每张都能找到合适的图片，可以用竖向排列的三张照片在放在一页中，随着介绍一幅一幅出现。

每个角色的介绍，一句话就够了，目前比较不足的是，没有突出 感受比知识更重要的点（或者与前面场景部分再加强一些联系会更好）。

![016](https://cloud.githubusercontent.com/assets/22133106/26035604/b4fa8e30-3901-11e7-8531-1bd1f8dbbd7f.jpeg)
### 17
![017](https://cloud.githubusercontent.com/assets/22133106/26035601/b4e923f2-3901-11e7-99d9-d48578c76c74.jpeg)
### 18
![018](https://cloud.githubusercontent.com/assets/22133106/26035602/b4e9f35e-3901-11e7-8128-831d3024fa4d.jpeg)
### 19

![019](https://cloud.githubusercontent.com/assets/22133106/26035605/b511a4ee-3901-11e7-8f88-3bb409a157e1.jpeg)
这部分最难，需要拆分成几页。文字上需要大幅修改（怎样更打动人），并找到合适的配图。

这部分可以加入更多公益的内容。

音乐在这里的节奏应该从舒缓，走向激昂，预示新的希望 和对未来事业的信心。

### 20
![020](https://cloud.githubusercontent.com/assets/22133106/26035607/b5156746-3901-11e7-8291-4ce9dfae8c2c.jpeg)
### 21
![021](https://cloud.githubusercontent.com/assets/22133106/26035606/b514c124-3901-11e7-928f-353869b1f5f0.jpeg)

**Comment by gabriel-guobin** [comment]
试着把我们的BP读了一下，有了更深的体会。
  
我们不是场景的展示，用干瘪的语言过度；也不是美景抒情，用华丽的词汇包装。

我们需要做到的，是从喜欢孩子、热衷教育的老师视角，引领家长、孩子开启一段自然探索和情感发现之旅。所以我们的文案就是仿佛在跟一个面对面的人讲故事，融入我的场景，激发你的想象，打开双方的共鸣。文字尽量朴实，精炼，可以加入一些口语化的词汇、甚至偶尔俏皮（这个夏爽读的版本可以有）。最后呈现的效果，BP图片上可能会删去一些文字，大家的文案主要通过配音的教师角色讲述出来。

**Comment by MuDemuder** [comment]
你是否在寻找一段旅程
带孩子出发
感知自然的呼吸
对抗岁月的倦怠和幻灭

碰巧，你遇到我（文字不用显示，图可用上面的）

**我带你去星空下**
栖居溪涧帐篷，仰望头顶浩瀚

用天文望远镜带孩子捕捉星星的笑脸
看它呼吸，看它行走
讲述天文源头的趣事
而不仅仅告诉它的名字

顺便
拍摄漫天星轨
带孩子穿越回梵高画布中的《星夜》
隔着时空，畅所欲言

感受一个画家对万物的情感
（梵高语录，可以不读，停顿一会儿。若读，最好找跟星空有关的。）

**我带你去雪山上**
藏身山间XX，俯瞰银装素裹

把厚厚的积雪
化身孩子梦中美景

用显微镜带孩子发现绚丽
一片片雪花独有的脉络
就如一个个生命
惊讶，感叹，呵护
就如发现了一座广寒宫

顺便
亲吻土地
听我朗诵
（雪山
用大雪填满飞机场周围的黑暗
雪山女神吃的是野兽穿的是鲜花
今夜 九十九座雪山高出天堂
使我彻夜难眠）（海子的，短一些，可以不用读了。）

**我带你走进「桃花源」**
触摸窑洞历史，远眺郁郁葱葱

仍孩子在油菜花海撒野
在「毛毛虫建筑」肚子里捉迷藏

悄悄追寻蜜蜂的脚步
来到它家
对神秘的蜂巢结构着迷

顺便
透露蜂巢建筑的内涵
引导孩子创造自己的作品

你追寻放松和惬意
可随我来到傍晚的露营竹屋，品当地美酒，饮嫩绿鲜茶
谈天说地

你说我不仅仅是教师（画外音，不打字）

我还是梵高门徒，痴迷自然（星空），寻找与孩子之间「基于乐趣的共享」。

我还是生命诗人，渴望感知（雪花），追寻孩子「强烈的感受」。

我还是建筑师，拥抱未来（蜂巢），探求唤起孩子「惊奇之心」。



希望听到孩子「真高兴我到这儿来了」（后面没想，先提交）
