### ISSUE TITLE
ch9 开头故事/场景的想法

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#23]
开头的场景或故事，可以先用文字发出。在添加一些思路的解释。

如果不好想，可以通过搜索相关关键词的图片找灵感。

**Comment by gabriel-guobin** [comment]
开头场景关键是触动人心，引起共鸣。

看了一下以前的资料。这个动画片，可能可以借鉴借鉴下。   
http://mp.weixin.qq.com/s?__biz=MjM5NTMzMjE2OQ==&mid=2652054709&idx=1&sn=9965e7aa81a03269a908d735c0a01cd3&chksm=bd1dad938a6a248544faaa249a5c1221ca3a8e8cbd62901b5c3afb0625c1b1f37a304cbf9327&mpshare=1&scene=1&srcid=0502L2DhKryG1qDQokXLZI3j#rd

**Comment by oliviayx** [comment]
你带孩子出发，想用旅行启迪孩子的心智，增加见闻  
你查攻略定计划，带孩子去看你眼中的世界，孩子却没有很高的兴致  
你带孩子去艺术、历史、名人的博物馆，文化大餐消化不了，孩子很快忘了看过的各种展品    
你带孩子亲近自然，面对孩子在旅途中热切而敏感的好奇，常感到力不从心，自己连两只鸟的种类都分不清如何教孩子
