### ISSUE TITLE
BP文字稿&修改意见收集

### ISSUE THREAD

**Issue by BravoCiao** [gabriel-guobin/ChildAcademy#24]
我带你去星空下
穿过紫云格凸河，仰望头顶的浩瀚。

孩子们争相说出星星的名字，
但我们讨论
星星之名如何带人类回家，
幕天席地，和他们想象星空

我们用天文望远镜，捕捉星星的笑脸，
地上的星星忍不住朝天上的星星喊话
拍摄漫天星轨，
带孩子穿越梵高画布
聆听星夜在不同时空的对话

感受一个画家对万物的喃喃细语

当我画一片麦田，
我希望人们感觉到麦子正朝着他们最后的成熟和绽放努力。
当我画一棵苹果树，
我希望人们能感受到苹果里面的果汁正把苹果皮撑开，
果核中的种子正在为结出果实奋进。

                    ——《亲爱的提奥》 文森特·梵高

我带你去雪山上
翻进崇礼雪场，闯入银色世界

积雪厚厚，穿过孩子魔法的指尖，
变成他们想象的形状
赋予喜怒与对白

屏息接住飘落的那朵雪花，
惊呼她生长的模样

细数纷纷飞扬
你带着孩子
随雪花翩翩起舞
我们放声欢笑，大声喊着
《雪花的快乐》
（徐志摩的诗如果要的话，裁剪能大声喊的内容）

我带你走进“桃花源”
任孩子们在油菜花田里捉迷藏
玩累了
爬进田埂边“毛毛虫”的房子
找水喝

追着花海里游戏的蝴蝶和蜜蜂
跟在蜜蜂身后，
悄悄探访他的家，
神秘的蜂巢结构令人着迷
孩子们忍不住动手建造我们的房子。

你可以趁机放松自己
随我来到傍晚的露营竹屋，品当地美酒，饮嫩绿鲜茶

你遇到的我
也许是曾痴迷梵高星空的美术工作者，不再执著分享梵高星夜的技法，而是带领大家领略梵高那，夜晚的天空不像是任何平凡双眼所见的世界。
也可能是流连于各地人情风土的编剧，更想和本真的孩子分享，和我们有生命联结的故事，比如亲吻一朵雪花，收取一枚银色童话。
还可能是设计顶楼视角的建筑师，期待用自然原本的语言与土地对话，充满惊喜的建造也回归人类对空间安全和舒适的追寻。

我们相信，在大自然面前，
感受它，远比了解它重要得多。
我们很容易说出花草树木的名字，
分辨岩石的种类，
但我们容易忽略他，
整体到部分、色彩和比例，几何与对称的原创隐喻。

对教育的追问，我们聚集而成
“童行书院”的驻地教师
因教育的热情，我们踏雪寻梅
让旅行的孩子浸润自然，自我发现与创造。

教育专业团队支撑驻地教师成长，
博物、美术、天文、戏剧
同一个人，多种探索
提供适合儿童旅途的教育陪伴

城市家庭的旅行收入，
反哺村落儿童的教育支持
同一群人，两种身份，
实践乡村教育可持续的公益投入。

未来，仿佛若有光
在每个美丽的角落，照亮我们一起同行。

大家有意见就在下面跟贴吧

**Comment by windflyinglx** [comment]
［先赞文案］

1.空间结构
四段的结构，最好是，星空——雪山——桃花源——画家的麦田，这样空间结构是从上至下的。

2.点题段放在前面 
我们相信，在大自然面前，
感受它，远比了解它重要得多。
我们很容易说出花草树木的名字，
分辨岩石的种类，
但我们容易忽略他，
整体到部分、色彩和比例，几何与对称的原创隐喻。

这段，最好放在所有感受之前，不然一来读下面的文字会有点摸不着头脑，二来这段文字分隔了逻辑上衔接顺畅的上下两段：
你遇到的我
也许是曾痴迷梵高星空的美术工作者，不再执著分享梵高星夜的技法，而是带领大家领略梵高那，夜晚的天空不像是任何平凡双眼所见的世界。
也可能是流连于各地人情风土的编剧，更想和本真的孩子分享，和我们有生命联结的故事，比如亲吻一朵雪花，收取一枚银色童话。
还可能是设计顶楼视角的建筑师，期待用自然原本的语言与土地对话，充满惊喜的建造也回归人类对空间安全和舒适的追寻。

对教育的追问，我们聚集而成
“童行书院”的驻地教师
因教育的热情，我们踏雪寻梅
让旅行的孩子浸润自然，自我发现与创造。

3.宣传语
因为看到别的组在征集宣传语，如果我们要有的话，可以是   童行书院，期待与你同行



最后再赞一下这两段：
教育专业团队支撑驻地教师成长，
博物、美术、天文、戏剧
同一个人，多种探索
提供适合儿童旅途的教育陪伴

城市家庭的旅行收入，
反哺村落儿童的教育支持
同一群人，两种身份，
实践乡村教育可持续的公益投入。

对童行书院的理解特别精辟，我觉得西西老师她们应该会很喜欢这两段。

**Comment by gabriel-guobin** [comment]
星星之名如何带人类回家，
>这一句不太明白是什么意思   

幕天席地，和他们想象星空      
>为什么在星空下，想象星空   


我的建议，是还是用这两句：
>「孩子们追问着星星的名字，
而我更愿分享的
是那遥远的未知与神秘，等待孩子们自己去探索」

因为通过这两句想要传递『 感受比知识更重要』的主题，通过向孩子们分享自己的思考，培养他们对未知的好奇和探索欲望


*我们用天文望远镜，捕捉星星的笑脸，*
*地上的星星忍不住朝天上的星星喊话*

>上面两句，建议不放在图片中，由夏霜读出来

**Comment by MuDemuder** [comment]
- 星空那段，“星星”较多，还有隐喻，是否引起不知所讲的感觉。
- 穿过孩子魔法的指尖，用“绕”如何。
- “蝴蝶”是否要提。
- 赞同直接把点题段放在前面，开篇先立意，再叙述三个场景，让观众明白重心在哪，因为这不算反转，不需要抖包袱。如果是这样的话，需要与星空那段中间穿插几句话。
- 一页上显示尽量不超过4句话。

**Comment by xiashuang613** [comment]
@MuDemuder 牧天提到的几个细节都很棒，尤其是“绕”那个。我早上重修改掉了星星一个和蝴蝶。关于星星部分提到的隐喻，我一时想不到代替的地方。字面理解，就是人类最早为什么为星星命名，为什么命这个名，星星在人类历史上的意义是什么，所以了解星星名字背后就是带人类回家。
另外，点题段，抽取上来，可在最后做keynote时操作，因为还有一个开头没有确定。暂且把小改动后的内容贴在这里。




我带你去星空下
穿过紫云格凸河，仰望头顶的浩瀚。

孩子们争相说出星星的名字，
但我们讨论
星星之名如何带人类回家，
幕天席地，和他们想象星空


我们用天文望远镜，捕捉闪亮的笑脸，
地上的星星忍不住朝天上的星星喊话
拍摄漫天星轨，
带孩子穿越梵高画布
聆听星夜在不同时空的对话

感受一个画家对万物的喃喃细语
当我画一片麦田，
我希望人们感觉到麦子正朝着他们最后的成熟和绽放努力。
当我画一棵苹果树，
我希望人们能感受到苹果里面的果汁正把苹果皮撑开，
果核中的种子正在为结出果实奋进。

                    ——《亲爱的提奥》 文森特·梵高

我带你去雪山上
翻进崇礼雪场，闯入银色世界

积雪厚厚，绕过孩子魔法的指尖，
变成他们想象的形状
赋予喜怒与对白

屏息接住飘落的那朵雪花，
惊呼她生长的模样


细数纷纷飞扬
你带着孩子
随雪花翩翩起舞
我们放声欢笑，大声喊着
《雪花的快乐》
（徐志摩的诗如果要的话，裁剪能大声喊的内容）

我带你走进“桃花源”
任孩子们在油菜花田里捉迷藏
玩累了
爬进田埂边“毛毛虫”的房子
找水喝

追着花海里游戏的蜜蜂
跟在他身后，
悄悄探访他们的家，
神秘的蜂巢结构令人着迷
孩子们忍不住动手建造我们的房子。

你可以趁机放松自己
随我来到傍晚的露营竹屋，品当地美酒，饮鲜嫩绿茶


你遇到的我
也许是曾痴迷梵高星空的美术工作者，不再执著勾画星夜的技法，而是带领大家领略梵高那夜晚的天空，不像是任何平凡双眼所见的世界。
也可能是流连于各地风土人情的编剧，更想和本真的孩子分享，和我们有生命联结的故事，比如亲吻一朵雪花，收取一枚银色童话。
还可能是设计顶楼视角的建筑师，期待用自然原本的语言与土地对话，充满惊喜的建造也回归空间安全和舒适的追寻。

我们相信，在大自然面前，
感受它，远比了解它重要得多。
我们容易说出花草树木的名字，
分辨岩石的种类，
但我们容易忽略他，
整体到部分、色彩和比例，几何与对称的原创隐喻。


对教育的追问，我们聚集而成
“童行书院”的驻地教师
因教育的热情，我们踏雪寻梅
让旅行的孩子浸润自然，自我发现与创造。


教育专业团队支撑驻地教师成长，
博物、美术、天文、戏剧
同一个人，多种探索
提供适合儿童旅途的教育陪伴

城市家庭的旅行收入，
反哺村落儿童的教育支持
同一群人，两种身份，
实践乡村教育可持续的公益投入。


未来，仿佛若有光
在每个美丽的角落，照亮我们一起同行。
