### ISSUE TITLE
ch10 BP路演准备

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#25]
主持人组给路演的同学的建议：
1. 针对自己项目的弱点，提前准备问题来回答；还可以像老树新芽一样，自问自答，准备好应对的答案。充分利用这二十分钟
2. 提前告诉主持人有哪些团队伙伴参加路演，以及是否有分工，比如哪部分由谁讲解／分享
3. 可以挖掘制作BP或团队协作中动人的点，回顾总结时候分享给大家

---

我们项目的路演时间为  20：20~20：40

1. 参加路演报名：建议大家所有人参加，最后与各位打个招呼。

2. 针对项目的弱点，以及大家可能会问到的问题，提前准备好答案。（大家可以先抛出可能的疑问）
- 大家可以抛出自己认为路演时，可能遇到的问题。如果有想好的答案最好也试着回答一下。

3. 挖掘BP制作过程中或者在项目思考中动人的点，可以分享给大家（对大家投片加分有好处）

请大家针对以上三点回复哦

* [ch10 BP路演准备 · Issue #25 · gabriel-guobin/ChildAcademy](https://github.com/gabriel-guobin/ChildAcademy/issues/25)

**Comment by oliviayx** [comment]
可能提出的问题：

1. 童行书院的最小故事是什么？

2. 这个旅游和市面上的夏令营最大的区别是什么？

3. 文案利用了认知写作学里的哪些原理？

4. 童行书院体现了人性的哪个方面？痛点是什么，如何呈现的？  

5. 童行书院文案中用了哪些隐喻？

6. 童行书院的亮点是什么？

7.  BP 的组块体现了什么次序与信息结构，是如何考量的？

**Comment by 2Forest** [comment]
可能的问题先想到这么多，可以通过问题揭示咱们通过文案中没有直接叙述出来的一些考虑，自夸一下^_^：

1， 童行书院如何处理旅行和公益的关系，BP中如何体现的？
2，项目过程中最难搞定的是哪一部分，最后如何克服？
3，BP组块间衔接的逻辑是什么？
4，BP中提到的活动都会在书院开展吗？

过程动人的点：
1，大家都非常投入，尤其是PK文案集中开zoom会议那一周，几乎觉得每天下班后正式工作才开始^_^
2，跟大家讨论集思广益的过程中体验到创作的心流。
3，被有些小朋友（们）的才华惊到，鞭策自己更加努力精进。

**Comment by gabriel-guobin** [comment]
2Forest  想到的问题
---
可能的问题先想到这么多，可以通过问题揭示咱们通过文案中没有直接叙述出来的一些考虑，自夸一下^_^：

1， 童行书院如何处理旅行和公益的关系，BP中如何体现的？
2，项目过程中最难搞定的是哪一部分，最后如何克服？
3，BP组块间衔接的逻辑是什么？
4，BP中提到的活动都会在书院开展吗？

过程动人的点：
1，大家都非常投入，尤其是PK文案集中开zoom会议那一周，几乎觉得每天下班后正式工作才开始^_^
2，跟大家讨论集思广益的过程中体验到创作的心流。
3，被有些小朋友（们）的才华惊到，鞭策自己更加努力精进。

**Comment by 2Forest** [comment]
1， 童行书院如何处理旅行和公益的关系，BP中如何体现的？

童行书院以通过向亲子旅行者提供教育产品的方式获得支持教育公益的资金。BP因为面向亲子旅行的决策者（年轻父母），所以主要通过为该类旅行者出游痛点提供更好的解决方案的方式介绍项目。为避免道德绑架之嫌，公益部分稍加弱化。

2，项目过程中最难搞定的是哪一部分，最后如何克服？

整合大家各个BP文案的逻辑线条。需要考虑哪部分在前更容易调动受众的情感。最后通过确定叙述人身份加以整合。

3，BP组块间衔接的逻辑是什么？

这个最后版本会把童行教师的身份介绍放在最前面吗？根据最新版说吧。

4，BP中提到的活动都会在书院开展吗？

BP中提到的场景都是根据目前童行书院所在地的特点设计的，且符合童行书院的教育理念。因为目前书院课程还在逐步开发中，相信最终课程肯定与这些场景有很多重合。

**Comment by gabriel-guobin** [comment]
夏霜帮忙一起改的：
### 童行书院与亲子旅游的夏令营的区别？具备哪些优势？

- 教师 VS 导游

  其中最核心的区别在于「领路人」上。自身专业素养较高的各行业工作者（编剧、画家等艺术家）加入童行书院教师的行列，他们在各自领域的专业性，以及在童行书院培训后，跨专业的整合能力也是一般亲子游夏令营中聘用的教师所不具备的。    
  童行书院项目的公益性，能够吸引众多有能力的小伙伴加入，驻地教师的工作内在动机尤显珍贵。


- 教育活动设计 VS 户外野营  

  另外童行书院「可持续公益」的探索获得了国内专业教育机构的支持。不但会对老师进行六个月的全面教育培训，还对教育理念和具体的教学娱乐活动上进行创新的探索，培养孩子对知识的内在渴望，发挥创造力。
![](markdown-img-paste-20170517182404460.png)





### 童行书院关注的是人性的哪个方面？

   - 人性矛盾： 好奇 VS 麻木
   - 痛点：  
   和儿童相关的行业，常常与教育挂钩，而传统教育中哪怕是走到自然中的旅行，所谓的自然科普其实是另一种形式的知识灌输，对于孩子来说，在大自然面前，感知比知识更重要。一旦唤起孩子的强烈感受，那么，对知识的渴求就来得顺理成章，并且会更加持久。
   - 如何呈现的：  
   分别以天文爱好者、编剧、画家的视角，带领孩子感受能够唤起深刻情感的体验。“为孩子铺就一条渴望知识的路”的意义远远大于我们现在所能给予他们的知识。



### BP组块间衔接的逻辑是什么？

- 带你去开启感官之旅的三个场景总体结构：

  - 我带你去星空下
  - 我带你去雪山上
  - 我带你走进「桃花源」

  对应空间上的仰视（星空）、俯视（地上的雪花）和容器隐喻（桃花源里）

- 三个场景内的活动特点：

  - 从大到小
  - 具象到抽象
  - 美丽的自然风景——细节的观察——产生新感觉

  遵循的规则是「引导而非灌输」、「少说教、多分享」、「观察、体验、然后说出你的感受」。希望的是从我们对每个场景的设计中，能够体现出来。




### 为什么不从公益出发

以公益之名行事，常有道德绑架之疑。尤其当旅行遇上公益，公益容易夺取公众眼球，忽略旅行本来的面目。
没有负担的旅行，顺手做公益，才可持续；当时不被绑架的旅行，才能表现其意义。
旅行的本身就是公益。

**Comment by gabriel-guobin** [comment]
#### 通过认知写作学的课程收获，体会「自我决定论」，引出BP中强调的项目核心优势。

![001](https://cloud.githubusercontent.com/assets/22133106/26164882/acd23558-3b60-11e7-91fc-6d41b271ee5d.jpeg)
![002](https://cloud.githubusercontent.com/assets/22133106/26164883/acfe3a18-3b60-11e7-849b-fdb663fafaff.jpeg)
![003](https://cloud.githubusercontent.com/assets/22133106/26164885/ad150fae-3b60-11e7-89ac-8191ee45d8fa.jpeg)
![004](https://cloud.githubusercontent.com/assets/22133106/26164884/ad14745e-3b60-11e7-9031-b0272a509f63.jpeg)
![005](https://cloud.githubusercontent.com/assets/22133106/26164886/ad1591a4-3b60-11e7-8db4-50414418dc09.jpeg)
![006](https://cloud.githubusercontent.com/assets/22133106/26164888/ad18bda2-3b60-11e7-83a3-42666fc808fc.jpeg)
![image](https://cloud.githubusercontent.com/assets/22133106/26556326/7f65108e-44cc-11e7-9e66-5b78bdf98737.png)
