### ISSUE TITLE
项目名称确立

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#3]
考虑到大家讨论都是在公共平台，很多资料难免外流，可能会对我们借鉴的真实公益项目带来负面影响。
需要大家献策，为结业项目取一个新的名称。

格式如下：
```
- 项目名称：考虑隐喻、记忆生存优势、修辞感觉  巴拉巴拉...
- 名称解读：最好的名称似乎好记好理解，不需要理由或说明。所以限制50字以内。
```

体会为人父母的感觉吧~

----

结业作品名称后期可改，非一次定稿。重在刻意练习认知写作学原理，顺带培养对项目的感情。请大家不带负担的畅所欲言。

**Comment by 54elim** [comment]
@gabriel-guobin 项目设定仍然是类似 童行书院 吗？

**Comment by gabriel-guobin** [comment]
@54elim 在没有更好的模式前，我们还是先借鉴童行书院的模式
当然如果在构思项目名称或者最小故事时候，能有其他的商业模式亮点是最好不过啦

**Comment by gabriel-guobin** [comment]
### 更新170415答疑，阳老对选择品牌名称的建议
  - 主题：跟旅游、儿童相关
  - 文化模因：基于天上有行云，人在行云里这样优美的诗句去找出一个品牌的词汇
   - 认知负荷：
     - 好写：笔画要比较简单
     - 好记：元音 ( AEIOU ) 比例要大于60%
	 （儿童相关的项目，元音比例足够大，小朋友和家人才记得住。）
  - 最小行动：动宾结构，突出最小行动，如「多背一公斤」，「陪孩子读诗」，认知负荷较小
