### ISSUE TITLE
项目进度时间表

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#4]
## 结业BP作品项目进度及每周安排

![image](https://cloud.githubusercontent.com/assets/22133106/25314636/83eae656-287a-11e7-8b3c-ff3d5fbaed23.png)

#### `里程碑`为每周的阶段性目标。

- 每周五 `d5` 晚24点前，完成里程碑的目标。

- 在[[6w] 结业项目提问公告 · Issue #165 · AIWriter/Writer004](https://github.com/AIWriter/Writer004/issues/165) 更新项目进展提出疑问。

- 每周六 `d6` 答疑，记录并思考阳老师对项目的点评。

- 每周六 `d6` 小组沟通，商讨改进方案，推进下周计划。

- 每周日、周一 `d0`-`d1`根据上周答疑和小组沟通，完成上周内容的修订。 Deadline 为 d1 24:00。

####  结业作品时间安排 文字版
```

```gantt
    title 结业作品时间安排
    section 课程进度
        5W 文采 :2017-04-09, 7d
        6W 文采 :7d
        7W 故事 :7d
        8W 大作业 :7d
        9W 大作业 :7d
        10W 结业:7d
        路演    :2017-5-15,5d
        结业典礼:2017-05-20, 1d
        
    section 项目确定
        成员招募    :2017-04-10, 2d
        最小故事    :2017-04-12, 12d
        组块 & 故事修整  :2017-4-17, 12d


    section 项目实施
        文案初稿      :2017-4-24, 7d
        设计构思      :2017-4-24, 7d
        文案润色      :2017-05-01, 7d
        详细设计      :2017-05-01, 7d
        视频构思      :2017-05-01, 7d
        视频制作      :2017-05-08, 7d
        最终修改      :2017-05-15, 1d
        
    section 里程碑|周六答疑
        故事构思: 2017-04-15, 2d
        故事框架: 2017-04-22, 2d
        故事完善: 2017-04-29, 2d
        文案初稿: 2017-04-29, 2d
        设计方案: 2017-04-29, 2d
        文案终稿: 2017-05-06, 2d
        设计终稿: 2017-05-06, 2d
        视频方案: 2017-05-06, 2d
        视频终稿: 2017-05-13, 2d
        课程收获复盘: 2017-05-20, 9d
```
```
```

---
来源：

- 课程时间安排：
    * [Home · AIWriter/Writer004 Wiki](https://github.com/AIWriter/Writer004/wiki)

- 甘特图生成：
    * [Cmd Markdown 编辑阅读器 - 作业部落出品](https://www.zybuluo.com/mdeditor#)

**Comment by gabriel-guobin** [comment]
纳博科夫以卡片为最小单位创作，我们也尝试以卡片形式，将结业作品拆分成小的里程碑。




课程剩下 7W、8W、9W 三周。最后一次阳老的答疑，是我们结业作品重要的里程碑。


采取主动认领任务的方式，开展分工。为每个里程碑挑选负责人，带领大家以卡片的形式。

- 大作业的四个阶段：

    - 故事 （ 7W完成）
    - 文案 （ 7W初稿，8W 完成）
    - 设计 （ 7W初稿，8W 完成）
    - 视频 （ 8W初稿，9W 完成）

每个阶段任务，以周为单位切割成小的里程碑。


- 各个阶段任务负责人的职责：

    - 故事 ：协调故事各条线索的展开，确定故事框架。
    - 文案 ：确定最终文稿，用文字触动内心。（可以组织大家以类似小作业的形式，就相同场景描写，刻意练习同时，博采众长）
    - 设计： 运用《设计与修辞》认知原理，迁移认知写作学，理论落地实践，
    - 视频： 带领大伙完成时空变形的人性魔术。


- 原则：认领其中的任务，并非自己单干，也不是放弃其他任务。而是作为任务的负责人，更好的组织大家聚焦关键目标，快写慢改。

回复参考格式：

```

    - 名号 ：
    - 认领组块：故事 / 文案 / 设计 / 视频 /
    - 想法： 

```

**Comment by windflyinglx** [comment]
17.4.23 第一次小组全体会议讨论内容
### 目标：完成最小故事雏形
#### 现实：发现童行书院的商业计划和我们之前的预期不符。书院主要面向城市中高产阶级，属旅行项目，公益成分不是很大。
#### 结果：按照商业和公益两个方向重构最小故事，周二晚上八点再次碰头，目标为完成最小故事雏形。

#### 本次讨论的部分笔记：
主要是夏霜所说的关于童行书院的部分
##### 牧天的笔记：
- 之前认识：旅行+公益
- 全面了解后，对公益的定位只是前期，后期的宣传并不会提公益：因为需求调查中，整个公益行业调查中。
- 重点：同样选择五星级旅游地的时候，会首先选择童行书院。
- 具体：
 - 每个家庭都有旅游的需求，那么有+1的，就可能会先选择于此
 - 对象：公众
 - 为什么选择：
  - 书院设计
  - 当地环境
  - 倡导更 浸润式旅行方式，透过独特旅行方式，可以选择来这边
 - 公益这个点，主要面向志愿者做传播和招募。因为志愿者可以面对当地留守儿童，但是比重不太大。
- 总结：旅行中，沉浸式旅行，到童行书院。

当然，也可以从志愿者的角度出发，说一个故事。

##### 李行之的笔记：
###### 竞争对象：其他五星级酒店。
有同样优美风景的地方，我会优先选择童行书院

###### 旅行：每个家庭都有旅行计划和需求，如果有＋1的需求，会优先选择童行书院。
不要被公益这两个字绑架，
楼那本地的自然环境的条件，

###### 公益：这个点面向志愿者
留守儿童占的比例不是很大。而不是能给当地的孩子带去什么，而不是给童行书院支持多少资金

###### 故事：从志愿者的角度和故事出发，应聘童行书院，成为志愿者的故事，以吸引更多的家庭去到这个地方

###### 定位：为什么说这个项目是非常成熟的一个闭环，因为他们的定位很明确。
面向对象：城市中高端家庭
童行书院有＋1，是这种好奇会驱动你来，而不是因为便宜你才来。

###### 惊喜：不侧重教育，童行书院会是一个惊喜。
就这个期间，涉及到相关的活动，可能是戏剧、美术等活动。中间会开展冬夏令营，来了就可以参加，周一到周三都不同。根据此节奏来参加。不强调教育的目的和意义。发现不一样的美，在别的地方看不到，在这个地方才有。
如何把握度？
从旅行的角度去宣传，可以加一点宣传，但是不能对教育期望过高。
文化旅游，但不会把文化这个点打出来。
能来这里参加这个项目的人，拥有的教育资源会不少。如果期望太高，会比较失望。会给你惊喜，但惊喜不要投射到教育方面。
一土学校和童行书院是不同的形态，不能做比较。

###### 教练的提示：时空变形
孩子：有新的空间来体验
家长：减少了很多负担
空间的变化，孩子在新的文化可以体验到不同的东西。
如果有作业要求，就用一个点去做会比较好。
花时间：做成keynote，排版，什么形式进行绘制，需要一个人尽早进入状态
大胆裁剪，只选一个主要要素

##### 本次讨论的一点心得体会：
###### 为不同类型写BP的苦恼不同：

- 对于自建产品，难度在于思考产品的商业功能和需求究竟是什么。

- 为已有产品做BP，因为用户和需求已经比较明显，不需要再次思考，难度在于构建故事，已有产品怎样打动人。相对来说，三者之中难度最小，但没有了探索琢磨的过程，乐趣也许也最少？

- 因为我们的BP所针对的项目是已有产品，且正在进行中，仅从外部、不同内部人员讨论分辨不出与其他同类项目的区别。此时与内部人员的沟通、弄清楚项目的内核和目标就显得尤为重要，而不能仅靠自己开脑洞构思。而且因为此产品还在进行中，尚未推广，其需求并未经过市场检验。哈哈，忽然有种带着镣铐跳舞的感觉，不过感觉也很有意思，尤其是在今晚跟大家讨论之后。很期待最后我们会磨合出一个什么样的作品。
###### 找准视角是写BP的关键
- 公益方向，目前似乎困在了视角上。璞童很想做的留守儿童视角，有风险，而童行书院提供的志愿者视角，并不受书院的重视和看好。踌躇中。
- 商业方向，可以用的视角很多，能否找到比较新鲜的视角以及逻辑合理的故事，是此方向的关键。

**Comment by gabriel-guobin** [comment]
@windflyinglx 虽然已有产品可发挥余地较小，但今天讨论的感觉很有意思。  

仿佛了解张爱玲的文风，原作看了一半，自己试着写结尾。

收到了小伙伴们的版本，最后还来了官方版。这不就是自我反馈，自己对照自己么。哈哈！

**Comment by windflyinglx** [comment]
自觉地抱走视频制作任务。
今天跟儿童微信助手的视频制作者聊了聊，稍微有了点儿底。他说主要是feel（其实应该更没底了），技术不难。

**Comment by gabriel-guobin** [comment]
@windflyinglx  我觉得你也可以挑战一下「故事」呦，

**Comment by violettianjie** [comment]
学习了。太佩服你们组了。项目进度颗粒管理这么好。

**Comment by gabriel-guobin** [comment]
@violettianjie 打自己脸了，默默把开头的【每周更新】删掉  %>_<%
