### ISSUE TITLE
ch6 线上沟通 结业项目进展和时间安排

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#5]
### 会议内容：

1. 分享：自己写的最小故事 和 对整体项目的构思

2. 提问：自己遇到的困难和对项目构思上的疑问

3. 讨论：结业作品 时间进度和分工安排
    -  [整体项目进度和每周`里程碑`](https://github.com/gabriel-guobin/ChildAcademy/issues/4)
    - 组员分工安排
    - 本周`里程碑`修改（下周一）
    - 下周`里程碑`计划（下周五）

### 会议时间和地址

- 时间：4月23日 20：00（北京时间） 建议提前15分钟进入链接

- zoom会议链接：https://zoom.us/j/9653599346

### 与会准备：

请回复本 Issue  想分享的内容/想要解决的问题+议程建议。例如：

```
 - 分享：自己的最小故事 和 对整体项目的构思
 - 提问：剖出好点子，征求其他人的想法。
 - 建议：调整方案，其他思路和参考资料。
```
  - 注：为了高效解决问题，大家提问姿势，都按提问格式将思路捋顺，跟帖或发问题链接皆可。

### 线上交流工具： zoom使用规范

- 建议统一 zoom 会议用户名与 GitHub 用户名

- 非发言时关闭话筒，避免自己环境噪音影响会议

- 提前进入会议，调试自己设备

- 遇到需要迟到或者早退，静默上下线，不干扰中断会议进行

- 客户端下载地址：https://zoom.us/download (电脑使用效果最佳)

### 会后及时总结，形成闭环

聚会结束 42 小时内把参与聚会收获回复在本 Issue 下，形成信息闭环，令众收益。

**Comment by gabriel-guobin** [comment]
## 会议前的任务：




 今天BP讨论很重要的结果是初步确立了故事的矛盾。  

 暂定的人性美德关键词是 :  
 - 正面：**“好奇心”(备选：感受、感知)**。  
 - 反面： **“乏味”（备选：麻木、淡漠）**


#### 请所有人（包括观察员哦）根据这对矛盾写出最小故事和作为隐喻的意向，线上开会时候讨论进行确定。

- 所有人都写的目的在于博采众长和统一思路。
- 请大家在会议前30分钟将，故事和意向提交到本issue.
- 其他的人性关键词和核心矛盾,如有好的想法也可以展开

### 答疑启发

今天阳老答疑是说最小故事的事件不重要。最重要的是提炼出与人性相关的核心矛盾。再根据这个矛盾去生发故事的事件就容易了。

![image](https://cloud.githubusercontent.com/assets/22133106/25307271/914a55ac-27d0-11e7-9473-af25cc6e392e.png)




## 灵感触发器

为什么想从**感受**作为核心词汇，大家可参考以下打动了我们的一段话

摘录《夏山学校》里的一段话：
>在师范学院或大学里给学生们讲课时，面对这些满腹无用知识的青年男女，我常对他们的幼稚感到惊讶，他们知道的很多，辩论对答如流，古文出口成章，但他们对人生的看法却幼稚如婴儿。**他们只被教会怎样了解，但未学到怎样感受**。这些学生很友善、和气与热情，却缺乏敏感性和用感性的知觉来引导思考的能力。**我给他们讲的是一个他们已经错过并再也回不去的世界**。

## 以人性矛盾写最小故事的思路



1. 可参考下图的模式，列出一个矛盾和两条主线。

     
![image](https://cloud.githubusercontent.com/assets/22133106/25307285/c915e316-27d0-11e7-9c5c-0f2901df2d5b.png)



  如：
  - 一个矛盾：好奇心VS乏味  /  感受力VS麻木
  - 两条主线：对事物的好奇才能激发自主探索的兴趣，强行灌输会更加乏味。

2. 按照英雄之旅的构架，添加事件，组合成最小故事

  
   ![image](https://cloud.githubusercontent.com/assets/22133106/25307276/a96bfce4-27d0-11e7-80f4-1e12f11dac45.png)



   按照英雄之旅的模型把 陪孩子读诗还原了一下。

   **可以仿照此结构写下你的最小故事**

   * [《陪孩子读诗》故事结构借鉴](https://github.com/gabriel-guobin/ChildAcademy/blob/master/AccompanyChildToReadPoetry.md)

**Comment by oliviayx** [comment]
# 守护心中的光
## 期望
- 你期望孩子的生活永远充满好奇
## 痛点
有多少次年幼的你提出思考很久的问题时，你的父母和老师告诫你好好读书，不要胡思乱想。

有多少次年幼的你探究与教科书无关的知识时，你的父母和老师告诫你好好读书，不要学那些没用的。

有多少次年幼的你痴迷于拆卸爸爸那个旧半导体时，你的父母告诫你好好读书，不要把家里的东西弄坏。

![bb76243e55b5572fa2a9b5599fd6ce49](https://cloud.githubusercontent.com/assets/26110756/25311985/16ee550e-2840-11e7-8c41-aa5ef1eb6591.jpg)
于是你不再关心小蚂蚁为什么能够搬得动比自己大好几倍的食物

于是你不再幻想外星人长成什么样子，他带你上飞船一起遨游太空

于是你不再捣鼓家里的各种旧电器，它们成为了一堆名副其实的破烂

你的心中少了为什么，再也不去提问，不去探究，甚至不去思考。机械的，机械的接受着教科书上的知识，机械的接受父母的安排，机械的按部就班。

。。。


多年后

从事与专业无关工作的你抱怨学习了那么多年无用的知识

对生活没有多少热情的你感受不到四季韵与蕴

你觉得生活总是少了点什么，内心有一个黑洞在不断的侵蚀你的能量

你看着别人活成了你想要的模样，而自己活成了你最不喜欢的模样

成为父母的你，看到孩子清澈明亮的眼中，泛着似曾相识的光

孩童稚气的口中问出的十万个为什么，冲洗着你内心的黑洞

冲刷过后竟露出了一丝光

你终于明白这光

是对世界好奇，和孩子眼中的光无二

你缺的是生动，对零度的偏离，对世界的好奇

**你想要守护自己心中的光，更想要守住孩子眼中的光**

**你害怕他眼中的光一不小心就溜走，害怕孩子也花上这许多年才明白内心之光的意义，如你一般**


## 矛盾

如今电子产品泛滥，特别容易吸引孩子的眼球，这样的娱乐方式无法守住孩子的好奇心

怎样的方式可以引导孩子的兴趣，守护孩子内心的好奇之光，苦无途径

## 经历磨难
报各种学习班，钢琴、画画、舞蹈、跆拳道

各种选择都是父母安排，孩子没有真正的自主权，并没有培养孩子真正的兴趣，孩子很快厌倦、放弃。

## 童行书院
这里有专业的团队，能够提供专业的引导（对父母和孩子共同引导）

接近大自然，激发孩子真正的兴趣

让孩子自主选择，树立远大的目标，找到学习的意义

能够帮助当地的留守儿童

守住所有孩子心中的光

**Comment by xiashuang613** [comment]
妈妈，你知道我们看到最亮的星星叫什么名字吗？
妈妈，银河真的能看见吗？
妈妈，牛郎星和织女星，他们在七夕会相见吗？
.............
8岁的男孩的生日礼物收到了爸爸送的一架天文望远镜，一堆和天文有关的书籍。

爸爸和妈妈的年假来了，全家每年都是在海边或者在某个风景区度过。孩子没有玩伴，换一个地方写完作业，就过完假期。

某年暑假，爸爸和妈妈忙到没有时间休年假，爸爸带着孩子出差到了楼纳，参加当地的一个会议，不得已带着小男孩出差。
小男孩在童行书院里，有新的玩伴，野外行走观察，彻夜观星，看见更美。

——以上为粗糙故事梗概。在和西西对聊后，有些关键点还没有能够结合，还需要磨合的。


西西的对谈中，更清晰了解童行书院项目的设计及背后理念，以至于选择视角的时候开始有些繁杂。
童行书院非常清晰的定位，就是面向城市的中上层家庭，毕竟书院是落地在五星级酒店。之前文案中的“旅行+公益 ”，公益二字更多是面向志愿者，招募志愿者前往；而面向城市家庭他们强调的是旅行，这里的旅行更加侧重在，去哪里都可以旅行，但不妨来童行书院，因为风景之外，五星级酒店不降低预期之外，还可以有童行书院开展的活动，让孩子更多元参与，参与户外、戏剧以及当地文化等等等。
面向城市家庭，和西西在以下几个点探讨到我们文案可能方向：
1、需求
所有的家庭都有旅行的计划和需求

2、好奇心
书院的建筑设计
楼纳的自然环境
浸润自然的旅行方式

3、公益
家长到当地旅行，顺手支持当地公益多长时间（强调是顺便的，并不是强求的）
（在这里强调到公益的时长问题，能够让志愿者在当地服务多长时间）

4、志愿者的故事
招募来的志愿者的身份、为何参与

**Comment by gabriel-guobin** [comment]
### 要点

- 一个矛盾：感受力VS麻木 （人性词汇：自由 VS 束缚 ）

- 两条主线：

  - 缺乏对人情、事物的感受力，导致思想僵化，沦为生活的奴隶。
  - 发现新感觉，体会世间万物的趣味，才会主动追寻生命的色彩。

---



### 痛点、矛盾

- 你通晓天文地理、可曾感受。。。

	- 你古文出口成章，可曾体会。。。

		- 你阅览画作百千，可曾对话。。。

---

（机器人隐喻：使人联想到当今教育的现实）
>机器人被植入一段程序、从此获得一项新技能。

>他可以按照你的意愿，满足对命令的所有期盼

>甚至可以和做游戏。
> 唯独失去了感受。



----

- 你希望孩子充满理性，坚强、独立、掌握生存的技能

    - 但「用感性的直觉来引导思考的能力 」只能在自由探索中发现。。

----

### 痛点 —— 场景再现（两条主线）

---
场景一：孩子在厌学、不愿做功课

古诗用不上，为什么要学
计算机什么数学题都能解，会用计算机就行了，干嘛被乘法口诀

---

场景二：家人带孩子感受大自然，自由玩耍

看山是山，看鸟是鸟

---

## 冲突 期望与现实的矛盾

孩子的生活割裂

书本知识越发枯燥

越发向往天空的小鸟和辽阔的草原

---
---

- 大人的生活
    - 年轻拼命闯荡，老了退休享福
    - 世界很大，我想去看看

- 折射孩子的未来

---

### 找出痛点原因，建立打击的对象   （美德缺陷产生的不良后果）

---

- 缺乏对世界的感受
    - 人与物（科学）
    - 人与人（人文）

- 学校没有教，父母也没有学过
-
----

 - 无法感受当下的美

   - 面对枯燥的工作时，人生开启了快进模式

---


### 建立目标: 抓住人性和美德，触动神经   

---


- 点燃孩子的好奇，自由探索和发现
  - 感受科学和人文之美
  - 将割裂的人生拼接




###  经历磨难  主要任务+ 对抗性因素


### 万能灵药


### 万能灵药 展示



### 英雄回归 ： 向往 （获得美德得到的优良结果）

**Comment by 2Forest** [comment]
我想的是以光为隐喻，从城市孩子妈妈和乡村留守儿童的语气分线，首段故意重复加强效果。

第一部分城市孩子的母亲：

小时候父母忙于工作/
能供吃穿于我/
却无暇顾及我的内心世界/
等到父母意识到/我已经长大了。    

当我有了自己的孩子/
他从小吃穿不愁/
我带他参加画画弹琴课外班/
却发现/
只是为了填补我内心曾经的缺失/
从物质到精神无所不缺的我/
是想要什么？       

内心深处仿佛有个洞
总在猝不及防时开裂/
我的生命能量也会从其中掉落/
我知道它在那里/
急于弥补它/
花了很长时间才在最深的黑暗处发现最迷人的光亮/
因为这束光/
我不再惧怕黑暗/
向着光前进/
风雨不舍。      

每个人心底都有的这束光/
我花了很长时间孤独寻找/
但我不希望我的孩子再耗费这么长的时光。       

第二部分留守儿童：
我的父母总是忙于工作/
能供吃穿给我/
却顾不上我是不是开心快乐/
我怕父母顾得上的时候/
我已经长大了。

第三部分城市妈妈：
这样的领悟不要再等一代人/
让我们从现在就开始寻找/
来童行书院/
寻找、呵护孩子心底的光
也照亮留守儿童成长的路。

上面的文字希望都是各自角色的画外音，可以配图片最好配小视频。

觉得接入童行书院的部分有点生硬。个人觉得比较满意的部分是城市妈妈和留守儿童自述的第一段形成的比照，如果不关心留守儿童，将形成一代人的鸿沟。

我对光的理解：我觉得“光”这里是指对外在内在世界的一种源源不断的积极向上的好奇心，内在驱动一个个体去追求真善美，追求完善自我同时利益他人。

**Comment by gabriel-guobin** [comment]
## 体会：

- 定位：旅行 + 1 （ 爱的体验 ）= 发现之旅
    - 爱的体验
        - 人类对浸润自然的天然需求
        - 父母对子女的爱（ 更加注重孩子本身的体验 ）
        - 支教老师对乡村孩子的爱 （ 爱是会传染的 ）

## 故事公式

- 一个矛盾：感受力 VS 麻木 （人性词汇：爱 VS 孤独/封闭 ）

- 两条主线：

    - 缺乏对人、事物的感受力，导致思想僵化，内心孤独。
    - 爱的氛围中，发现新感觉，体会世间万物的趣味，追寻生命色彩。

------

欢迎小伙伴拼接下文。

格式如下：

```
##  痛点（ 核心矛盾的对比） 
    ( 4句话 内）
### 痛点 —— 场景再现（两条主线）
    ( 4句话 内）
### 场景一：
    ( 4句话 内）
### 场景二：
    ( 4句话 内）
### 冲突 期望与现实的矛盾
    ( 4句话 内）
## 找出痛点原因，建立打击的对象   （美德缺陷产生的不良后果）
    ( 4句话 内）
### 建立目标: 抓住人性和美德，触动神经   
    ( 4句话 内）
###  经历磨难  主要任务+ 对抗性因素
    ( 4句话 内）
## 万能灵药
    ( 4句话 内）
### 万能灵药 展示
    ( 4句话 内）
## 英雄回归 ： 向往 （获得美德得到的优良结果）
    ( 4句话 内）
```

**Comment by MuDemuder** [comment]
# 模板

##  痛点

- 自然赋予人类种种，人类自古又向往自然（图腾、火种、星空？）；
- 家庭都希冀于旅游，那旅游如何才能有意义？
- 城市中，我们如机器人，那天性为何？唤醒和激发个体生命激情从何做起？
- 孩童成长不能一味培训，娱乐时间不能被电子产品所占据，那如何做到寓教于乐，如何才能有效利用到电子产品？
- 成人带着孩子一同旅游，是否会嫌孩童太吵，占据自己宝贵休闲时光？

- 注意：隐喻不能多，机器人不选择；选择星空与云朵两个可以吗？

### 痛点 —— 场景再现（两条主线）

##### 场景一：

- 城市中：成人早起一副累瘫模样，弓着腰；出门时刻突然穿的光鲜亮丽，腰杆挺直。带给成人烦恼的，除了生活，还有孩子——每天除了上课、培训就吵着玩电子产品，看电视。
- 或者：成人赚钱之余出门旅游，想要亲子上阵却感压力重大——游玩同时兼顾看管孩子，使得旅游成了带孩子负担。

##### 场景二：

- 楼兰（例子）：父母带着孩子来到了这儿，孩子托给童行书院，父母放开手脚，孩子也接触新事物。在旅程结束后，父母发现孩子新变化。

### 冲突 期望与现实的矛盾

云朵和星空不是自然的，是存在每个人心中。

## 找出痛点原因，建立打击的对象   （美德缺陷产生的不良后果）

- 孩童在生活学习中缺乏与自然互动。
	- 互动不是简单旅游，不是不去思考，就能抓住的。
	- 如何看星空，如何与他人协作，如何感知世间万物，这也是一门教育科学

### 建立目标: 抓住人性和美德，触动神经   

## 瞎想

心怀宇宙张连城。。。

# 整体布置

儿童需要「学习+玩耍」这两场景，写着写着发现的。

## 最小故事

- 故事一：父母带孩子去楼兰旅游，将孩子托管给童行书院，自个儿选择自驾游。
- 故事二：孩子在书院娱乐学习的场景。
- 故事三：孩子觉得在书院带领下玩的很开心，父母无需管孩子也很开心。

## 流程（第一稿）

#### 组快一（儿童的确需要学习+旅游）（这组块没安排好，顺序和内容）

儿童旅行的秘密，你们知道在哪吗？

锻炼身体？放飞天性？增强动手能力？提升协作能力？还是。。。

（沉默）

那你们再带着儿童旅行时，是否发现儿童琐事多，显得旅游更加疲劳？但若放在家中，恐怕不仅仅是儿童的折腾，心无法安定，还要担心没人看管下（其他人看管下），电子产品的侵蚀？那放在儿童培训班呢？能教导什么？

复杂世界来临，对多维度知识要求拔高，普通儿童培训班只能教会儿童学习单科目，那真正跨学科大牛是如何产生的？

（沉默）

#### 组块二（童行书院如何达到学习+旅游）

（没想好）

#### 组块三（学习+旅游，合二为一）

是让儿童沉浸于自然中，寓教于乐同时，学到迁移能力。

#### 组快四

在城市，看到一朵白云，孩子拉着家长的手，说：这和那边的云好像啊。

涉及到楼兰的话，借鉴[楼兰实践直播间](http://xw.qq.com/c/dy/2340/20170406A09Q7200)

**Comment by 2Forest** [comment]
快写如下，欢迎拍砖：

【暑假前】

【晚上妈妈】

快暑假了，想带他出去玩，可是大城市基本上都去过了，就那几个著名景点，人多又热，每次他累我们也累。实在想不起来，干脆就问问他的意见吧！民主决策嘛！

【晚上孩子独白】

妈妈说暑假要带我去旅行！耶！

她还说我已经八岁了，可以自己想一下想去哪里、想玩什么。

去哪里呢？恩，这个问题太难了，因为我知道的地方太少了，我才七岁！我知道的地方都去过了！北京，上海，西安，哦，还有海南。

想玩什么……这个……不知道我想玩的妈妈会不会愿意！

那么先说说我不想怎么玩吧。我不想出去玩的时候妈妈老是看手机不理我！

我不想每次出去逛博物馆看那么多文物，我知道它们很珍贵，可我记不住！

我不想每次去海边的时候妈妈总是跟爸爸喝啤酒聊天，我都快无聊死了，还不许我跑太远。

我也不想每次出去玩的时候一堆人挤来挤去，我被挤在大人堆里都快喘不过气来了。

我也不想跟着妈妈逛商场，给我买东西我也不想跟着去！好不容易放假了，我想出去好好玩儿！

我想玩什么呢？

我偷偷告诉你，你说妈妈会不会说我。我平时看到妈妈买回家的猪肉跟书上的猪长得很不一样啊，我知道猪肉跟猪是不一样，但是为什么书里的猪也都不一样呢？我还没有见过猪呢。

还有，我听说有一种虫子叫萤火虫，它们在晚上出来身上闪闪发光，我好想亲眼看看，它们把电放在自己肚子里，不会被电死吗？为什么妈妈每次看到我插插座都超级紧张。我要是把它放在手里，它会电到我吗？

还有，你说有苹果树、梨树、为什么没有西红柿树？西红柿跟苹果差不多大呀。小枣那么小听说都长在树上呢！我想看看西红柿是怎么长的，不长在树上，能长在哪呢？

这样的问题我还有一大筐呢，妈妈总说我是问题篓子，很多她也不知道怎么回答我。

哦还有，我喜欢盖房子，可是除了用积木和乐高盖，我还没有见过真正的房子是怎么建的呢！每次看到有人在建造楼房，我想凑近了瞧瞧的时候，妈妈都不让我去，她说太危险了，还很脏。唉。

我到现在也还没有好好看过星星呢！我是说一堆一堆的真星星。在海边的时候看到过一次，但是爸爸妈妈说不要在外面待得太晚，就把我带回酒店去了。全国的酒店都长得差不多呢，没什么意思。

……渐渐入梦。

【早晨妈妈】

向孩子征求了意见，这下让我头更大了，看看他说的那些喜欢和不喜欢，我该去哪里给他找个合心意的地方过暑假呢？

网上浏览、手机浏览、等方式出现童行书院暑期项目海报。

哎呀太好了，试试这个吧！孩子动手动脑动心的时候，正好我自己也可以充充电呢。 

【暑假后】

孩子看着窗外的云，忽然大笑：妈妈快来看，那片云彩好像咱们暑假时候看到的那只牛啊！

【孩子妈妈】他以前从来没注意过天上的云彩……

**Comment by 2Forest** [comment]
太晕了，七岁还是八岁那里，我改小了一点，忘了统一了，囧~

**Comment by windflyinglx** [comment]
17.4.26 最小故事星空传奇

带孩子真累。
这不是抱怨，这是此情此景下，我这个当爹的一番肺腑之言。
家有八岁黄口小儿，平时在家各种兴趣班补习班就别说了，哪知道好不容易出门旅行，也还是一样不得消停。
“爸爸，我要吃这个！”
“妈妈，我要买那个！”
这哪里是旅行，是实地版的淘宝吧。
好不容易坐下来看看星星，也不让我闲着。
“爸爸，老师说天上的星星都有名字的，那个星星叫什么啊？”
“这……给，自己去查星图软件吧，让你老爸我歇一会儿”
“……”（孩子不开心状）
“爸爸，这棵树叫什么名字啊？”
“不知道。”
“那只鸟从来没见过呢，是什么鸟啊？”
“自己去查。”
“哼，旅行真没意思！”
哎，如果能有人来教教孩子这些，就好了。

（科学老师出现）
“哇，好高端的望远镜！简直是观测星空的利器！我来教你看星星吧！”
“好啊！”
“你看，那是福禄寿三星，冬季天空最亮的三颗星，又被称为猎户座的腰带。”
“啊，连起来是很像一根带子啊。”
“那是猎户座的宝剑，那是参宿四……”
“原来金牛的眼睛真的有点儿红啊！”

看着孩子一像一朵小火苗被点燃的热情，我这才渐渐觉得，这才是旅行应有的样子。
天悬星河，星汉灿烂。
我们正如星空中散落的星沙，唯有经那指星之手，才能熠熠闪耀。
