### ISSUE TITLE
参考素材汇聚地

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#6]
借鉴其他组的想法，开了这么个贴子，有启发的都往这里丢吧！    

可以直接把连接贴上去。   

最好加上一句话，描述自己看的时候，得到的启发。

>来自阿杰的提议：
我们还是去学习一下阳老师和教练们推荐的往期优秀的项目实践，看时也要写卡片，然后可以把卡片和学习笔记也放到github 里，关键是结合我们目前的想法，看的时候说不定会有更好的创意。

---
借鉴帖：
* [参考素材汇聚地 · Issue #2 · Mina-yy/BPstory](https://github.com/Mina-yy/BPstory/issues/2)

**Comment by oliviayx** [comment]
2010年《国家地理》频道宣传广告文案
　
If you are, you breath..

　　If you breath, you talk.

　　If you talk, you ask. .

　　If you ask, you think.

　　If you think, you search.

　　If you search, you experience.

　　If you experience, you learn.

　　If you learn, you grow.

　　If you grow, you wish.

　　If you wish, you find.

　　And if you find… you doubt.

　　If you doubt, you question.

　　If you question, you understand..

　　If you understand, you know.

　　And if you know, you want to know more.

　　And if you want to know more, you are… alive.

这段文字可以唤醒麻木的都市人，激活心中的探索和旅行欲望。

**Comment by gabriel-guobin** [comment]
## 以「感受」为主题的素材清单：


### 启发


#### 用经历讲道理

* [“我爱艺术，但绝不让孩子上美术课” | 一位任性台湾妈妈的自白 | 少年商学院](http://parents.youthmba.com/archives/13388)

>孤单寂寞的时候，他也许会想起：“以前妈妈曾经在这个美术馆跟我讲过马格利特的故事。”他会记得，还没上小学呢，妈妈就对他大讲特讲超现实主义，那种比手画脚的疯狂行径让多少旁人睁大眼睛。他会知道，他的妈妈，愿意去感受生活中所有细腻的细节，并且分享给他。而这种感受美好的能力，正是我最期望他能养成的。


#### 用故事讲道理

* [章鱼的爱情：法国大学生拍给青少年的启蒙短片 | 少年商学院](http://parents.youthmba.com/archives/6366)

####  用故事启发你的感受和思考（淡化是非）

* [请做“田鼠阿佛”的家人 | 少年商学院](http://parents.youthmba.com/archives/999)

>几乎所有好绘本都不说教人生道理。它们津津乐道的多半是一段经历、一个过程、一个有趣的生活片段。
>作为妈妈，我必然面对这样的考验，要不要强硬地把自己对社会的判定和经验告诉他。这有点像塞给他一把武器，尽可能多地保证他不受伤害——可是，从此他就要负戈旅行了啊。

>在我看来，《田鼠阿佛》不是写给阿佛，更多是写给李欧·李奥尼心目中的“理想家人”——给孩子足够多的时间，放手让他自己去体验世界，去和世界万物交流。让他缓慢地、甚至屡次受挫地、按照自己的历程发现自我，发现美，也发现丑。




### 提醒：


* [感受力，让我们的内心力量生生不息 | 芭学堂_李跃儿芭学园_传送门](http://chuansong.me/n/428696544660)

  提醒自己不要写成这种清单式文章，而是让人愿意传播的故事。

* [谁说3岁以内不记事，就不用带TA去看世界](http://weibo.com/ttarticle/p/show?id=2309404090611920701681&infeed=1)

  有些观点可用，场景也串联了故事，但观点略散（尤其后面），还是不够打动人

### 开阔思路

几篇清单，纯粹开阔思路，寻找角度


* [讓孩子在旅行中學習解決問題 -奇蜜父母學習中心 - -奇蜜父母學習中心 - 親子學習 - 信誼奇蜜親子網](http://parent.kimy.com.tw/new/arTicle.aspx?g_id=3&id=5223)

* [带孩子旅行的四重意义 | 少年商学院](http://parents.youthmba.com/archives/5402)


### 素材

以漫画表现场景，串联故事。其中有些好素材，说不懂能用到。


* [漫画丨荷兰孩子12岁前一定要做的50项户外活动 | 少年商学院](http://parents.youthmba.com/archives/11902)

**Comment by gabriel-guobin** [comment]
### 《田鼠阿佛》的創作背景

1985年，曾有一群一年級的小學生透過電話訪問了李歐．李奧尼，當時他告訴小朋友，他最喜歡的作品是《田鼠阿佛》。阿佛是一隻田鼠，和他的家人住在一起，當其他的田鼠都忙著為冬天儲糧時，他卻在一旁無所事事。冬天來臨時，別的田鼠問阿佛儲存了什麼東西？阿佛則展露了他的詩人身份，他收集的是景色、聲音、氣味與印象，他為其他田鼠朗誦了一首詩----這雖然不是實際的糧食，但卻是精神糧食。

在《伊索寓言》中，好吃懶做的蚱蜢註定有悲慘的下場，但是李歐．李奧尼的想法卻恰恰相反，他褒揚了身為一個藝術家的榮耀，更重要的是，身為一個受人肯定與賞識的藝術家，更是一種至高至上的光榮。大人總是教導孩子們，要尊敬政治家、科學家或愛國志士的貢獻，因為他們的影響力是顯而易見的，但是藝術家的價值卻是抽象而難以捉摸的，而且藝術並不是人們生活的必要條件，因為它不能拯救非洲的孩子們免於飢荒，也不能讓中東的孩子們遠離戰爭，那麼，藝術和詩詞的價值究竟何在呢？田鼠阿佛幫我們解答了這個疑問，他用美麗的詩詞讓其他飢餓憤怒的老鼠們，在濕冷的冬天裡感覺陽光的溫暖、看到花朵的顏色，阿佛的詩為同伴們的心靈注入了愉悅的影像，滋養了他們的身心。藝術擴展人類的想像力，引領我們看到美好的事物，給予我們無窮的希望！

李歐．李奧尼在創作《田鼠阿佛》時，再度加入了他的個人經驗。他在接受Agree的訪問時曾表示，他在創作《小黑魚》時熱衷政治，之後，他「變得比較內省，而且開始覺得……身為一個藝術家就足以證明自己的價值了……或許應該根據這個想法來發揮成一個故事。」（Agree, "Lionni's Artichokes: An Interview"）

阿佛沒有加入其他現實、唯物論的田鼠之列，就像李奧尼一樣，他並不需要汲汲營營追求什麼。阿佛豐富了其他田鼠的心靈，就像李奧尼的藝術一樣，吸引了所有喜愛他的讀者與評論家。李歐．李奧尼藉由田鼠，表達了他對自己的認同感。

---

来源 ：  
* [走進李歐‧李奧尼的世界](http://www.kimy.com.tw/project/200304/leo-loa/index_3.asp)

**Comment by gabriel-guobin** [comment]
以下梳理，来自「晴妈说」公众号文章。有助于我们把握项目的要点

* [童行：在思想的王国里人人平等](http://mp.weixin.qq.com/s?__biz=MzA4MDg2Mzk1MQ==&mid=2698949105&idx=1&sn=d0224dc4a17352e4ae323e74b8fb8069&chksm=bab7a6518dc02f4700aeb5faa5efed9ea4fe682c2d6090e1ad852d1cd9c196511cf0b02859d0&mpshare=1&scene=1&srcid=0429a0fCo2FTU6aZIpjrK0Mg##)
----

## 初心

- 我们希望做什么样的公益呢？

  **在童行，我们有一个核心理念，希望做以“尊重”为核心的公益。**我们希望谁也不向谁倾斜，让每一个人获得面对面的平等的尊重。

  这可能做到吗？人世间的富足与匮乏，是如此明显而根深蒂固，有可能让人站在平等的地位上吗？

  **我们想说，在财富的王国高下有别，但在思想的王国人人平等。**

  如果我们想做平等的公益，就肯定需要建立思想的平台。没有施舍与被施舍，只有思想相互交流，相互尊重。

  公益不是施舍。天下为公，人人受益。

## 思考
深刻思想的产生仅由一件事决定：**你有多用力地思考生活**

>这个世界上，思想的产生并不由财富决定。确实，财富带来的眼界会促进思想火花，财富的贫瘠往往让人缺乏思想资源。但更多时候，深刻思想的产生仅由一件事决定：**你有多用力地思考生活。**而这种力度并不是由财富带来的，恰恰相反，很多时候，让人久久不能转开目光像锥子扎入皮肤一样狠狠盯住生活的动力，来自于困窘，来自于压力，来自于遍寻不到出路的迷茫。

>**那些思想，只是缺少途径转化为创造的力量，缺少积极改进的方法**。久而久之让人失去希望，因此范雨素才如此之少。

## 理念
- 要做**以儿童为中心的创造力教育**。我们向往的是让每个孩子都能**自我发现**、自我生成的人格教育。创造是让自我思想显形。


## 方法

- 想做高水平公益教育，首先需要做高水平教育
    - 北京筹备长期的创造力课堂。既是教育创新的探索，也作为教学方法研究和长期的教师培训。

    - **儿童交流的平台**
      - 给大城市和贫困山区的孩子开同样的课，对城市一般家庭收费，对流动儿童和留守儿童免费。
      - 让两边的孩子做同样有创造力的活动，编导戏剧、设计飞船、写故事、画画。再让两边的孩子在共同的平台上交流作品，在童行书院组织共同的儿童工作坊和艺术节。
      - 孩子的心是一样的，都有灵感可以转化为作品。当他们有了自己的创作，一定想要交流，在交流中互相受益。**唯有创造，才有四海一家的公益。**
      
## 未来

**童行计划定义：一个让孩子找到自己未来之路的计划**

![](http://mmbiz.qpic.cn/mmbiz_gif/7akam0l8SMzib2HJCCNJ3iaiaN8FbrmXsUGiarmSgCrI4hXnKnkw1ExwdqCWrkmGJI6n7wQ1lQHSXCw4wBpAicYPUBg/0?wx_fmt=gif&tp=webp&wxfrom=5&wx_lazy=1)

>我们将引入真实行业的行家，让孩子尝试创造的同时，也体验不同的未来人生。我们称之为“遇见平行宇宙中未来的你”

未来的童行计划由两部分构成：

- **童行星球，WePlanets，思维方式培养和创造性人格生成，Slogan是：Create Yourself. **以创造力为核心开设长期课外课。目前的总部在北京，会在一个四合院里开始我们的第一个课堂。

- **童行书院，WeLibrary，山水之间的自然教育和公益教育，Slogan是：Share the Futur**e. 让旅行的孩子亲近自然，山里的孩子看看外面。未来可以与各种有情怀的度假村开展合作。

- **曾经最喜欢书里的两个意象**：
麦田里的守望者，小王子的飞行员。
> 这可能代表了孩子心里对教育者的最好想象。**孩子们需要一个安全丰富的环境，可以放心地自由奔跑。与此同时有人在身旁聆听，尊重孩子的每个念头，相信他心里的小星球和玫瑰花。**

![](http://mmbiz.qpic.cn/mmbiz_jpg/7akam0l8SMzib2HJCCNJ3iaiaN8FbrmXsUGgtx2e9EiciaHCu2xggVRTw9SmbS8QNG16eYan8icKMib0z2VAoPKucUmDA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1)

**Comment by gabriel-guobin** [comment]
#### 优秀动画作品

* [你剪断了我的翅膀，却怪我不会飞翔 | 8分钟零台词却获117项提名64项大奖](http://mp.weixin.qq.com/s?__biz=MjM5NTMzMjE2OQ==&mid=2652054709&idx=1&sn=9965e7aa81a03269a908d735c0a01cd3&chksm=bd1dad938a6a248544faaa249a5c1221ca3a8e8cbd62901b5c3afb0625c1b1f37a304cbf9327&mpshare=1&scene=1&srcid=0502L2DhKryG1qDQokXLZI3j#rd)

* [值得孩子看百遍！10部奥斯卡最佳动画短片](http://mp.weixin.qq.com/s?__biz=MjM5NTMzMjE2OQ==&mid=209875099&idx=1&sn=dfc8f05657e0e9ce34834f5d8a7e1677&mpshare=1&scene=1&srcid=0502AYz8Z042kQcJSu2stvg0#rd)

---

#### 行动卡

练习故事思维，尝试用认知写作学原理解析一下这些动画好在哪里

**Comment by gabriel-guobin** [comment]
# 参考阳老的一篇旧文，可从产品设计的角度，分析「童行书院」项目

---
# 产品设计的本质是什么？


* [产品设计的本质是什么-阳志平， 2011年1月24日](https://www.slideshare.net/ouyangzhiping/ss-6693507)

---

## 平庸心理学家的思维方式

- 研究课题： ipad， pc机与笔记本对Y的
- Y=用户满意度 or 主观幸福感 or...

## 平庸产品经理的思维方式

1. 市面上已有A产品， A产品已经具备B， C，D， E， F......等27种特征
 - 因此，我们决定开发一款具备25种或者29种特征的产品
2. 公司具备A,B,C,D四种能力或资源
  - 因此，我们决定开发一款能体现公司这四种优势的产品

## 卓越心理学家的思维方式

- 通过A，找到一个与众不同的X  
- A=系统性思维；批判性思维；个人体悟...
- 通过精巧的实验设计，将X对Y的影响最大化
- 卓越心理学家的实验设计=放大器
* 例子：塞里格曼的习得无助实验（为什么不一上来就用大象与人类？）；卡尼曼的决策实验（为什么不一上来就用幸福这个变量？）

## 卓越产品经理的思维方式
- 通过A，找到一个与众不同的X
- A=系统性思维；批判性思维；个人体悟...
- 通过产品设计，将X对Y的差异最大化
- Y=用户体验 or 其它时髦词汇
- 卓越产品经理的产品设计=放大器
- 例子： ipad（触觉与便携性）

## 平庸与卓越的差异在哪？
- 卓越：发现并创造；
- 平庸：追随并重复；
- 卓越的科学家：创造变量以及发现原本并不存在的变量之间的关系
- 平庸：使用的所有变量（或规则；术语；心智模式）来自既有世界

## 自变量
- 你寻找到的自变量新鲜还是陈腐？
- 你寻找到的自变量符合人们既有心智模式还是需要付出较大认知努力？
- 你寻找到的自变量在时间与空间两个维度上可以如何改变世界，还是可以马上被抛弃？

## 因变量

- 所有的因变量都是在时间与空间，两个关键性问题上直接或者间接做努力
- 时间：反应时；时间的长度（实用性与沉迷）
- 空间：结构；位置（便携性）；次序
- 题外话：真善美是什么？真善美在时间与空间两个维度上是如何展开的？

## 衡量卓越心理学家的指标
- 研究效果量
- 效果量是不依赖于样本大小、反映自变量和因变量关联强度的指标

## 衡量卓越产品设计的指标

- 如何用研究效果量的思路来评价一个产品设计的好坏
- 好的产品设计：就是一个放大器，放大从X到Y

## 变量的实与虚
- 心理学的产品设计的特殊问题：变量多务虚
- 如何将这些务虚的变量实化？
- 虚对虚的产品设计与虚对实的产品设计，在用户反应时上的差异如何？


## 不同产品经理的添加剂
- 卓越的心理学家：受到各自教育背景；流派；性格等的影响
- 产品设计同样如此
  - 添加剂：中介变量；人口学变量；调节变量
  - 2011年流行的变量：情感化与社会化；移动；云计算；物理计算

## 总结
- 卓越与平庸并不是体现在常规工作而是创意工作
- 社会为你的常规工作付出的是薪水；为你的创意工作付出的是股份。
- 产品经理的常规工作：产品文档撰写；竞争情报调研；用户研究； ......
- 产品经理的本质工作：精心构建放大器

## 作业
- 分析3个卓越产品设计中的自变量；因变量及放大器各自是什么
- 分析3篇卓越的心理学实验设计论文中的自变量；因变量及放大器各自是什么
- 这些实验设计与卓越产品为了实现放大器，添加了哪些添加剂？

## 补充阅读
- 野中郁次朗与胜见明：创新的本质

**Comment by gabriel-guobin** [comment]
## 学习影片中的过度手法。如何用旁白引导听众的思路。

* [【白蘭氏創造力種子學程】激發孩子的潛能，讓他們瞭解自我，更加勇敢追夢 - YouTube](https://www.youtube.com/watch?v=puUYZuI3tow)

>
# 一个偏乡小女孩 从不敢有梦到追梦的故事

##  1.画面： 小女孩的照片、姓名、年龄介绍
- 问：你未来的梦想，或是想要做的事情是什么？
- 答：不知道
## 2. 单独页面的文字旁白
- 偏乡的孩子，对于未来总是感到迷茫
- 有些是不愿想，有些则是不敢想。。。

## 2.画面：辅导员采访视频，
- “乡村偏僻，投入的资源少，小朋友积极度和自信度较市区小朋友有差距。"

## 3. 单独文字页面：
- 他们不是缺乏潜力，只是需要
- 被看见、被倾听、被关注、被发掘。。。

## 4. 画面：孩子们画画的场面
- 孩子：学习怎么发挥艺术美感
- 孩子：感觉自己好像一个艺术家，然后做完作品很有成就感
- 老师：给他们一个平台，让他们能够跟艺术家一起参与创作，甚至因为这些作品可以让设计的民众看到，那对小朋友来讲都会是一个很棒的经验。


- 画面中的旁白：
    - 发掘孩子的创造力
    - 启发学习热情，他们会更有自信！

## 5. 单独文字旁白
- 激发孩子潜能
- 建立自信，更加勇敢追梦

## 6.项目背景和团队介绍
- 左半边 文字说明，右半边 视频或画面
    - 白兰氏三年来已辅导全台近400位偏乡孩子开启潜能、建立自信

## 7. 画面采访:呼应开头的痛点

- 之前采访的女孩：我未来的梦想是当一个
- 设计师（笑着说，满含自信）

-

**Comment by gabriel-guobin** [comment]
## 动画做的不错

* [Memory~銳普PPT大賽獲獎作品 - YouTube](https://www.youtube.com/watch?v=F-x54f0sn18)

**Comment by gabriel-guobin** [comment]
## 背景音乐与故事的契合

* [开智学堂认知写作学二期课程路演项目——亲族故事航行公司_腾讯视频](https://v.qq.com/x/page/c0300qmtkf7.html)

**Comment by gabriel-guobin** [comment]
## 其他亲子游产品和服务

* [“童游亲子营”与“麦淘亲子游”商业模式对比分析_亲子研学旅行农业项目开发_新浪博客](http://blog.sina.com.cn/s/blog_13cb9a7f00102wptv.html)

>两种模式都共同的强调亲子游活动中的社交属性，一方面是小朋友之间的广泛社交，另一方面是家长之间的社交需求也被充分考虑.

* [【专家视角】麦淘亲子游CEO：亲子游的重点不是旅游_网易财经](http://money.163.com/16/0524/15/BNRGPCA400253B0H.html)

>相同产品没有任何平台比麦淘买的好，原因在于**亲子游的核心不在旅游**。  
旅游只是陪伴孩子成长的场景和手段之一。我认为，**亲子游应该是一个介于教育、旅游两者之间的产物**。

>麦淘追求的是**创新和体验**，我们希望输出的是一种有“教育内容”的产品，而传统旅行社恐怕无法胜任。比如我们组织的“野外露营”活动，让孩子们在亲近自然中观望星空，“跟着院士挖恐龙”活动，让孩子们实地挖掘恐龙化石。“科学实验室”活动，让孩子现场感受神奇的物理化学现象的同时学到科学知识。

**Comment by gabriel-guobin** [comment]
* [高清视频素材网站有那些？？ - 知乎](https://www.zhihu.com/question/22449745)

* [Free stock videos – Pexels Videos](https://videos.pexels.com/)

* [Distill: Free HD Stock Video & HD Video Clips](http://www.wedistill.io/categories/nature)

* [Unsplash | Free High-Resolution Photos](https://unsplash.com/)
