### ISSUE TITLE
ch7 线上沟通 结业项目进展和时间安排

### ISSUE THREAD

**Issue by gabriel-guobin** [gabriel-guobin/ChildAcademy#7]
- 周三-4月26日 ：

    每人完成一个文字版 Keynote, 21：30前提交。22：00 开会讨论。夏霜负责筛选和拼接出最终的故事版本，并提出对文案和配图的要求。

- 周四-4月27日：
    请大家在夏霜的故事基础上修改和补充文案，并提交建议到本issue（可开始自己尝试制作keynote版本)。文案由 璞童 协调整理，图片由 珞洛 协调整理。

- 周五-4月28日：
    在18：00 前，郭斌和李行之一起完成 demo@bravo 美化修改。。

ch8 @MuDemuder 和@xgh007 大显身手，对文案精修

**Comment by oliviayx** [comment]
# 2017.4.26
## 旅行的意义
旅行的意义是什么？

是站在不同地标，吃着各式美食，成为朋友圈里让人羡慕的图片

还是扫荡罗马、巴黎、纽约、洛杉矶的街头，不停变换地方购物场所

是逃离压得你无法呼吸，每天不止8小时的工作和24小时不间断的家庭生活

还是带着孩子带着书包，在星级酒店里孩子做着奥数你玩着手机

是旅行结束你回到办公室，身体的疲惫比连续加班几日更严重

还是旅行前的期盼，旅行后的懊悔
## 


我不能告诉你旅行有什么意义

除非你亲睹过**楼纳**夜空的星光，密密麻麻织成一张网，包裹着身处银河系偏僻荒凉旋臂上，微小的太阳系中，这颗渺小蓝色星球上的人们。银河中流淌着你我的血液，对来自星海的人类有着谜一般的吸引力，我们的母体宇宙，在召唤我们回家，回归到本该属于我们的地方，就像粒粟掉入谷仓，滴水回归大海。

不过，这也谈不上有什么意义

除非你躬身以孩子的身份，用孩童的眼睛，借孩子的心，拨开遮在眼前的窗帘，拭去蒙在心间的灰尘，褪去身上的伪装，去听种子挣脱外壳发出的初生活力，去闻花朵绽放的生命，去看蜜蜂酿出的香甜。打开你所有的感官，你能找回对万物的好奇，拥有孩童探索世界的动力，你能找到驱使你不放弃的光。

不过，这也谈不上有什么意义

除非你带着孩子来到童行书院，在优美的景区，感受自然的魅力。在楼纳的星空中寻找发着红光的金星，握着孩子的手指划出孩子的星座，呼吸着牛儿嚼过的青草味的空气，用脚步丈量这一方纯净的土地，漫游在目力能及的云朵之中，在自然中打开孩子的心，走进孩子的心。




## 尾声

回到城市，天边的晚霞成为陪你回家的伙伴，星空成为了滋养你的源泉，天空变成了最好的画家，和孩子的想象力一起勾勒曾陪你们在童行书院景区玩耍的小牛和小羊，你和孩子一样期待着再一次去童行书院的旅行。


耗净了所有脑细胞，还是无法把童行书院的部分加进去，好尴尬。

---

又重新回味了一遍，珞洛的文字真美，好多金句。

**Comment by 2Forest** [comment]
【暑假前】

【晚上妈妈】

快暑假了，想带他出去玩，可是大城市基本上都去过了，就那几个著名景点，人多又热，每次他累我们也累。实在想不起来，干脆就问问他的意见吧！民主决策嘛！

【晚上孩子独白】

妈妈说暑假要带我去旅行！耶！

她还说我已经八岁了，可以自己想一下想去哪里、想玩什么。

去哪里呢？恩，这个问题太难了，因为我知道的地方太少了，我才七岁！我知道的地方都去过了！北京，上海，西安，哦，还有海南。

想玩什么……这个……不知道我想玩的妈妈会不会愿意！

那么先说说我不想怎么玩吧。我不想出去玩的时候妈妈老是看手机不理我！

我不想每次出去逛博物馆看那么多文物，我知道它们很珍贵，可我记不住！

我不想每次去海边的时候妈妈总是跟爸爸喝啤酒聊天，我都快无聊死了，还不许我跑太远。

我也不想每次出去玩的时候一堆人挤来挤去，我被挤在大人堆里都快喘不过气来了。

我也不想跟着妈妈逛商场，给我买东西我也不想跟着去！好不容易放假了，我想出去好好玩儿！

我想玩什么呢？

我偷偷告诉你，你说妈妈会不会说我。我平时看到妈妈买回家的猪肉跟书上的猪长得很不一样啊，我知道猪肉跟猪是不一样，但是为什么书里的猪也都不一样呢？我还没有见过猪呢。

还有，我听说有一种虫子叫萤火虫，它们在晚上出来身上闪闪发光，我好想亲眼看看，它们把电放在自己肚子里，不会被电死吗？为什么妈妈每次看到我插插座都超级紧张。我要是把它放在手里，它会电到我吗？

还有，你说有苹果树、梨树、为什么没有西红柿树？西红柿跟苹果差不多大呀。小枣那么小听说都长在树上呢！我想看看西红柿是怎么长的，不长在树上，能长在哪呢？

这样的问题我还有一大筐呢，妈妈总说我是问题篓子，很多她也不知道怎么回答我。

哦还有，我喜欢盖房子，可是除了用积木和乐高盖，我还没有见过真正的房子是怎么建的呢！每次看到有人在建造楼房，我想凑近了瞧瞧的时候，妈妈都不让我去，她说太危险了，还很脏。唉。

我到现在也还没有好好看过星星呢！我是说一堆一堆的真星星。在海边的时候看到过一次，但是爸爸妈妈说不要在外面待得太晚，就把我带回酒店去了。全国的酒店都长得差不多呢，没什么意思。

……渐渐入梦。

【早晨妈妈】

向孩子征求了意见，这下让我头更大了，看看他说的那些喜欢和不喜欢，我该去哪里给他找个合心意的地方过暑假呢？

网上浏览、手机浏览、等方式出现童行书院暑期项目海报。

哎呀太好了，试试这个吧！孩子动手动脑动心的时候，正好我自己也可以充充电呢。 

【暑假后】

孩子看着窗外的云，忽然大笑：妈妈快来看，那片云彩好像咱们暑假时候看到的那只牛啊！

【孩子妈妈】他以前从来没注意过天上的云彩……

**Comment by 2Forest** [comment]
唉，又忘了改了，七岁，我想统一改成七岁……

**Comment by gabriel-guobin** [comment]
我是一只小小鸟
飞过红色的草原，飞过蓝色的海面
我能听懂人类的语言，却听不懂其他鸟儿的歌声与快乐

----
我是一个机器人，植入一段意愿，输出所有期盼
连感受都是

----

你希望孩子充满理性，掌握生存的技能
可曾想过花儿与阳光也会带来力量

----

有这样一个故事

冬天快来临时，田鼠们忙着收集玉米、坚果、小麦、米杆，只有阿佛老默默呆在角落里。

----
当其他田鼠问它：“阿佛你为什么不干活”时，它就耷拉着眼皮回答：“我在干活吖——我在采集阳光、因为冬天很冷；
我在采集颜色，因为冬天是灰色的；我在采集词语，因为冬天日子又长又多，我们会把话说完的。”
听完他的解释，田鼠家人什么也没说，忙碌去了。

---
冬天真的来了。小田鼠们躲进山洞里，一开始，他们有很多东西可以吃，还有许多苯狐狸和傻猫咪的故事可以说。
可后来，食物被吃光了，它们进入真正缓慢、沉默、难熬的隆冬，谁也不想开口说话。。

----

阿佛爬上一块大石头，开始把他收集的那些东西，分享给大家。
「现在我把太阳的光撒给你们，你们是不是也感觉到那金色的光芒……」
四只小田鼠开始觉得暖和多了。那是阿佛的声音吗？还是魔术？

阿佛说起蓝色的长春花，黄色麦田里的红罂粟，和莓子树叶里的绿叶子。
阿佛说著，田鼠他们清清楚楚的看到所有的颜色，彷彿有人把颜色涂在他们的心头上似的。

这时候，他们问阿佛：“你的那些东西呢？”阿佛就开始向他们描绘，描绘阳光、五彩缤纷的颜色，为他们念很长的诗鼓劲。田鼠阿佛的家人们纷纷鼓掌喝彩。

----

孩子对世界的体验，不是大人感受的复制
带他（她）发现自然的美，去和世界万物交流。

----





场景：一幅画作前沉思（最好是生存优势意向）
用心感受世界的美好和凄凉，不去判断生活中的是与非



----

星空下：父母给孩子讲述宇宙的奥秘（配图）
把这些美好的东西装在心里就可以，不用非得记录在照片上

----

孩子与孩子（一个孩子带领一帮孩子探索任务的图片）
接触过的每个人，感受到的每一种情绪，都会成为他人格的力量


----

人应该学习“感受世界”，而不是“记住世界”



---

![image](https://cloud.githubusercontent.com/assets/22133106/25438292/8ed140da-2acb-11e7-98d5-542812938505.png)

感受生动，就在你身边

**Comment by xiashuang613** [comment]
十年前
一个人。旅行是我在天地间行走，肩上背包，双脚丈量山川湖海，只身穿过人山人海，风吹和悦，三人良睦，听渔民农人的故事，驻足流浪者的歌。止步海岛边，潮起潮落，幻想过驾舟扬帆，寻找我的港口。
八年前
我遇见他。旅行是不需要节拍的双人舞。他在的地方就是最美风景，星高海阔，日落霞光只看得见，彼此唇红齿白，眉目含情。密密麻麻的星空如网笼罩下，两人影却敢叫板，跳跃的星辰是我的心跳，闪耀的星光是许你的钻戒。
五年前
我们见到ta，旅行像带着麻烦精，挑剔且艰难。暂别公司和学校，全家齐聚，只是换一个地方入睡，吃饭，玩玩具。要有些不安分的计划，麻烦精跳出来说，安不安全，有不有趣，真不真实？只能去游乐场，才有玩伴？要去原始森林，才能看见原生草木吗？
旅行，带上ta，就会消失吗

童行，和你同行，带你看见一家人的旅行。（这里的转折没有找一个最佳点）

孩子的世界，一起玩就是好朋友，不论肤色，不分地域，没有贫富，笑脸绽放。他们不必知道带领他们玩的老师多么厉害，观星月，赏花木，探虫鱼；我们知道他和同龄伙伴在一起，是我们陪伴给不了的爱；他身后的童行老师，带领孩子躺在风中穿过花海的时刻在我们所有旅途中不可替代。
和ta童行的旅程，偶然划拉一份两人时间。浩瀚无际的星途能够靠近，跨过银河找到那颗钻戒，再戴一次。告诉ta，那颗心跳在你出生很久之前出现。
和童行一起，偶然山风吹过，我听见遥远的海浪声，带着港口的日照，乎乎的热潮涌上脸颊，偷得浮生半日闲。

**Comment by xiashuang613** [comment]
**十年前**
一个人。旅行是我在天地间行走，肩上背包，双脚丈量山川湖海，只身穿过人山人海，风吹和悦，三人良睦，听渔民农人的故事，驻足流浪者的歌。止步海岛边，潮起潮落，幻想过驾舟扬帆，寻找我的港口。

**八年前**
我遇见他。旅行是不需要节拍的双人舞。他在的地方就是最美风景，星高海阔，日落霞光只看得见，彼此唇红齿白，眉目含情。密密麻麻的星空如网笼罩下，两人影却敢叫板，跳跃的星辰是我的心跳，闪耀的星光是许你的钻戒。

**五年前**
我们见到ta，旅行像带着麻烦精，挑剔且艰难。暂别公司和学校，全家齐聚，只是换一个地方入睡，吃饭，玩玩具。要有些不安分的计划，麻烦精跳出来说，安不安全，有不有趣，真不真实？只能去游乐场，才有玩伴？要去原始森林，才能看见原生草木吗？

旅行，带上ta，就会消失吗

童行，和你同行，带你看见一家人的旅行。（这里的转折没有找一个最佳点）

孩子的世界，一起玩就是好朋友，不论肤色，不分地域，没有贫富，笑脸绽放。他们不必知道带领他们玩的老师多么厉害，观星月，赏花木，探虫鱼；我们知道他和同龄伙伴在一起，是我们陪伴给不了的爱；他身后的童行老师，带领孩子躺在风中穿过花海的时刻在我们所有旅途中不可替代。

和ta童行的旅程，偶然划拉一份两人时间。浩瀚无际的星途能够靠近，跨过银河找到那颗钻戒，再戴一次。告诉ta，那颗心跳在你出生很久之前出现。

和童行一起，偶然山风吹过，我听见遥远的海浪声，带着港口的日照，乎乎的热潮涌上脸颊，偷得浮生半日闲。

**Comment by windflyinglx** [comment]
晚上一直在加班……会前二十分钟写的，捂脸。

带孩子真累。
这不是抱怨，这是此情此景下，我这个当爹的一番肺腑之言。
家有八岁黄口小儿，平时在家各种兴趣班补习班就别说了，哪知道好不容易出门旅行，也还是一样不得消停。
“爸爸，我要吃这个！”
“妈妈，我要买那个！”
这哪里是旅行，是实地版的淘宝吧。
好不容易坐下来看看星星，也不让我闲着。
“爸爸，老师说天上的星星都有名字的，那个星星叫什么啊？”
“这……给，自己去查星图软件吧，让你老爸我歇一会儿”
“……”（孩子不开心状）
“爸爸，这棵树叫什么名字啊？”
“不知道。”
“那只鸟从来没见过呢，是什么鸟啊？”
“自己去查。”
“哼，旅行真没意思！”
哎，如果能有人来教教孩子这些，就好了。

（科学老师出现）
“哇，好高端的望远镜！简直是观测星空的利器！我来教你看星星吧！”
“好啊！”
“你看，那是福禄寿三星，冬季天空最亮的三颗星，又被称为猎户座的腰带。”
“啊，连起来是很像一根带子啊。”
“那是猎户座的宝剑，那是参宿四……”
“原来金牛的眼睛真的有点儿红啊！”

看着孩子一像一朵小火苗被点燃的热情，我这才渐渐觉得，这才是旅行应有的样子。
天悬星河，星汉灿烂。
我们正如星空中散落的星沙，唯有经那指星之手，才能熠熠闪耀。

**Comment by xiashuang613** [comment]
我曾经以为，我能给孩子全然的爱，书本能带给他所有知识。我一直坚持陪孩子阅读。

**城市** 
卧室，夜晚，妈妈和孩子亲子阅读《田鼠阿佛》
妈妈：“冬天快来临时，田鼠们忙着收集玉米、坚果、小麦、米杆，只有阿佛老默默呆在角落里。 当其他田鼠问它：“阿佛你为什么不干活”时，它就耷拉着眼皮回答 ”
妈妈&孩子：“我在干活吖——我在采集阳光、因为冬天的日子又冷又黑；我在采集颜色，因为冬天是灰色的；我在采集词语，因为冬天日子又长又多，我们会把话说完的。”
孩子：妈妈，阳光和颜色怎么采集呀，还有词语？
妈妈：你觉得可以有什么方法采集？
孩子：用手机！手机可以录下说的话，还可以拍照片。
妈妈：这是你的做法，很特别。我们先继续看阿佛怎么做。
“可是他们一点一点地啃光了几乎所有的坚果和浆果，禾杆没了，玉米也成为了回忆。石墙里很冷，没有人想要聊天。这时他们想起了阿佛说起过的阳光、颜色和词语。“怎么样，阿佛，你的那些东西呢？”他们问。
“闭上眼睛，”阿佛边说着爬上一块大石头，“现在，我带给你们阳光。你们感觉到了吗？它的金色光芒……”就在阿佛说到太阳的时候，那四只小田鼠开始感觉暖和些了。那是阿佛的声音吗？它有魔力吗？”。
孩子睡眼朦胧，强撑眼皮问：妈妈，是真的魔力吗？
妈妈一笑，继续念：“阿佛，那颜色呢？”他们充满渴望地问道。“再闭起眼睛，”阿佛说。
（妈妈的声音，越来越小）“还有词语呢，阿佛？”阿佛清了清嗓子，等了一会儿，然后，就像站在舞台上那样，他说,
孩子睡着。
妈妈轻声：当阿佛说完时，他们一起鼓掌喝彩。“好啊，阿佛，”他们说，“你是个诗人，真想不到！”
合上书页，妈妈看着孩子叹息：要是冬天来临，你能感受太阳，看见颜色，会念诗吗？手机要是没电，该怎么办？妈妈希望你像阿佛一样，不用手机也可以采集。

**童行书院**
孩子：妈妈，你看我像不像阿佛，我在采集阳光！
今天老师教我采集颜色哦，用眼睛看花的颜色，用耳朵听花的呼吸，然后和花说话，用心听花开的声音。我们还用画笔画下来了！
老师说，明天晚上要去摘星星，和楼纳的小朋友一起去山上，我们也一起去好不好，先去摘星星，后天再回家，可以吗？

**城市**   
卧室，妈妈和孩子的亲子阅读时间
孩子：妈妈，我们再读一遍《田鼠阿佛》好不好？
妈妈： 当其他田鼠问它：“阿佛你为什么不干活”时，它就耷拉着眼皮回答 ”
妈妈&孩子：“我在干活吖——我在采集阳光、因为冬天的日子又冷又黑；我在采集颜色，因为冬天是灰色的；我在采集词语，因为冬天日子又长又多，我们会把话说完的。”
孩子：我也会采集！
妈妈：于是他跟他们说起蓝色的长春花，长在黄色麦田里的红色的罂粟花，还有草莓丛中的绿叶子。阿佛说着，他们就清清楚楚地看见了那些颜色，就好像画在他们的脑子里一样。
妈妈：“还有词语呢，阿佛？”阿佛清了清嗓子，等了一会儿，然后，就像站在舞台上那样，他说：
孩子：“谁在天上撒雪花？谁融化地上的冰块？谁会把天气变好？谁又会把天气变坏？谁让四叶幸运草在六月里生长？谁熄灭了阳光？谁又把月儿点亮？”
妈妈大声：当阿佛说完时，他们一起鼓掌喝彩。“好啊，阿佛，”他们说，“你是个诗人，真想不到！”

孩子对世界的认识，需要一本本童书的养分。可他对真实的认知，需要自己去采集，童行带领他，我会陪着他。

**Comment by gabriel-guobin** [comment]
## 夏霜的BP文案已经发出来了，以更加生动活泼的对话式来表达。

目前的 BP思路如下：
- 方向：教育的角度，强调童行书院 旅行和发现 给孩子带来的影响。
- 故事：暂时取用  小田鼠阿佛 的故事，
- 关键词：感受力、发现
- 矛盾：生活的苟且 与 诗和远方 ，
- 目的：启发父母重视培养孩子的感受力

## 请大家在夏霜的故事基础上修改和补充文案，并提交你的建议。  
（可以自己尝试keynote版本，按照keynote的格式制作，不需要提交keynote版）

逐句评论方式：已经将此issue的留言迁移到了 仓库的文件夹中。
点击以下链接后，直接在句子或字词处，点击 +  在弹出的对话框中提出建议。

https://github.com/gabriel-guobin/ChildAcademy/commit/8659811edc5af0dd4c1618fcbaa9dad5e0c8d732#diff-355d748f21c08ee8360966bf447e5f47


1. 按照认知写作课原理，大胆裁剪。
2. 更有文采（润色文字）
3. 补充你心中的画面（找图）

## 修改依据（与认知写作结合）

- [BP 制作建议](https://github.com/AIWriter/Writer004/wiki/InfoBPTips)



## 其他参考

- [ 认知写作学参考手册 后面的BP部分](https://github.com/AIWriter/Writer004/wiki/InfoBPQA) 浏览密码 openmind

 * [BP 制作 QA 集锦](https://github.com/AIWriter/Writer004/wiki/InfoBPQA)
